- package.json
- src/components/sbb-accordion-item/sbb-accordion-item.stories.js
- src/components/sbb-accordion/sbb-accordion.stories.js
- src/components/sbb-button/sbb-button.stories.js
- src/components/sbb-card-badge/sbb-card-badge.stories.js
- src/components/sbb-card-product/sbb-card-product.stories.js
- src/components/sbb-footer/sbb-footer.stories.js
- src/components/sbb-grid/sbb-grid.stories.js
- src/components/sbb-journey-header/sbb-journey-header.stories.js
- src/components/sbb-link-button/sbb-link-button.stories.js
- src/components/sbb-link-list/sbb-link-list.stories.js
- src/components/sbb-link/sbb-link.stories.js
- src/components/sbb-logo/sbb-logo.stories.js
- src/components/sbb-section/sbb-section.stories.js
- src/components/sbb-signet/sbb-signet.stories.js
- src/components/sbb-stack/sbb-stack.stories.js
- src/components/sbb-title/sbb-title.stories.js
- src/pages/home/home--logged-in.stories.js
- src/pages/home/home.stories.js
- yarn.lock
Update `@sbb-esta/lyne-design-tokens` to version 0.1.5, which allows imports directly from the package root.
> fix: update design tokens and adapt imports

- src/components/sbb-form-field/sbb-form-field.e2e.ts
- src/components/sbb-form-field/sbb-form-field.scss
- src/components/sbb-form-field/sbb-form-field.spec.ts
- src/components/sbb-form-field/sbb-form-field.tsx
- src/components/sbb-link-list/sbb-link-list.spec.ts
- src/components/sbb-link-list/sbb-link-list.tsx
- src/global/helpers/observe-named-slot-changes.ts
- stencil.config.ts
We have various use cases where we want to remove or render an entire section of elements, depending on whether a specific element is slotted into a named slot.
This PR introduces functionality to define a named slot state and a way to observe the light DOM of the host for changes.
> refactor: introduce possibility to observe host for named slot changes

- src/components/sbb-button/sbb-button.tsx
- src/components/sbb-card/sbb-card.e2e.ts
- src/components/sbb-card/sbb-card.scss
- src/components/sbb-card/sbb-card.spec.ts
- src/components/sbb-card/sbb-card.tsx
- src/components/sbb-link/sbb-link.tsx
- src/global/interfaces/link-button-properties.spec.ts
- src/global/interfaces/link-button-properties.ts
- since all the components that implement the `LinkButtonProperties` need to set some variables in `render` function (basic case: set the tag name to \<a\> or \<button\> based on the href value),  a new helper function named `resolveRenderVariables` has been added, in order to provide default values for static, link and button cases with the following logic:
- if static, return a `span` with the attributes given by `getLinkButtonBaseAttributeList`;
- if href, return an `a` with the attributes given by `getLinkAttributeList` and the correct value for `screenReaderNewWindowInfo`;
- …
> feat: improvement in LinkButtonProperties interface

- _index.scss
- package.json
With this PR our sass code can be used by consumers (e.g. via `@import "@sbb-esta/lyne-components";`).
This is still experimental and sass code in our code base WILL change in the future.
> feat: add experimental sass output

- .github/actions/yarn-install/action.yml
- .github/workflows/continuous-integration-secure.yml
- .github/workflows/release.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> build: migrate GitHub Actions set-output to $GITHUB_OUTPUT

- src/components.d.ts
- src/components/sbb-dialog/readme.md
- src/components/sbb-dialog/sbb-dialog.spec.ts
- src/components/sbb-dialog/sbb-dialog.stories.js
- src/components/sbb-dialog/sbb-dialog.tsx
Extend `sbb-dialog` with option to close dialog via `sbb-dialog-close` attribute.
> feat(sbb-dialog): add `sbb-dialog-close` attribute option to close the dialog

- src/components.d.ts
- src/components/sbb-menu/readme.md
- src/components/sbb-menu/sbb-menu.e2e.ts
- src/components/sbb-menu/sbb-menu.events.ts
- src/components/sbb-menu/sbb-menu.scss
- src/components/sbb-menu/sbb-menu.stories.js
- src/components/sbb-menu/sbb-menu.tsx
- src/components/sbb-tooltip/readme.md
- src/components/sbb-tooltip/sbb-tooltip.scss
- src/components/sbb-tooltip/sbb-tooltip.stories.js
- src/components/sbb-tooltip/sbb-tooltip.tsx
**BREAKING CHANGE:** 
Use `open` for opening overlays and `close` for closing overlays. The methods `present()` and `dismiss()` become `open()` and `close()`; the tooltip properties `showDelay` and `hideDelay` become `openDelay` and `closeDelay`.
> refactor(sbb-menu): rename opening and closing methods

- src/components/sbb-icon/readme.md
- src/components/sbb-icon/request.ts
- src/components/sbb-icon/sbb-icon.tsx
This PR will allow the namespace `picto` to retrieve pictograms (e.g. `<sbb-icon name="picto:feuerloescher"></sbb-icon>`).
> feat(sbb-icon): add pictogram namespace

- src/components/sbb-alert/sbb-alert.scss
- src/components/sbb-alert/sbb-alert.spec.ts
- src/components/sbb-alert/sbb-alert.tsx
- src/components/sbb-card-product/sbb-card-product.scss
- src/components/sbb-card-product/sbb-card-product.stories.js
- src/components/sbb-card/sbb-card.scss
- src/components/sbb-dialog/sbb-dialog.scss
- src/components/sbb-dialog/sbb-dialog.stories.js
- src/components/sbb-grid/sbb-grid.stories.js
- src/components/sbb-journey-header/sbb-journey-header.scss
- src/components/sbb-link-list/sbb-link-list.scss
- src/components/sbb-link-list/sbb-link-list.tsx
- src/components/sbb-teaser/sbb-teaser.scss
- src/components/sbb-title/readme.md
- src/components/sbb-title/sbb-title.scss
- src/components/sbb-wagon/sbb-wagon.scss
- src/global/helpers/chromatic.js
- src/global/styles/mixins/typo.scss
- src/storybook/pages/home/home--logged-in.stories.js
- src/storybook/pages/home/home.stories.js
- src/storybook/styles/typography/readme.md
- src/storybook/styles/typography/typography.stories.js
Title mixins and `<sbb-title>`-component now have a default margin block to meet design specs. In the mixin you can opt out by passing the flag $exclude-spacing with true (e.g. `@include text-1($exclude-spacing: true)`).
In the `sbb-title` component you can just set any margin from outside on the `<sbb-title>` itself, e.g. `<sbb-title style='margin:0'>`.
> feat: add title margins

- src/components.d.ts
- src/components/sbb-toggle-check/readme.md
- src/components/sbb-toggle-check/sbb-toggle-check.e2e.ts
- src/components/sbb-toggle-check/sbb-toggle-check.scss
- src/components/sbb-toggle-check/sbb-toggle-check.spec.ts
- src/components/sbb-toggle-check/sbb-toggle-check.stories.js
- src/components/sbb-toggle-check/sbb-toggle-check.tsx
Rename property `icon` to `icon-name` to be consistent with all other components.
This PR Closes #1532 
> refactor(sbb-toggle-check): introduce new design

- src/components/sbb-navigation-section/sbb-navigation-section.scss
- src/components/sbb-navigation-section/sbb-navigation-section.stories.js
This fix only works if there is exactly one button and if it is an "sbb-button".
Closes #1575
> fix(sbb-navigation-section): place button always in new row

- src/global/styles/typography.scss
- src/storybook/styles/typography/readme.md
- src/storybook/styles/typography/typography.stories.js
Renamed CSS class `sbb-text-bold` to `sbb-text--bold` to match BEM naming.
> fix(typography): fix name of `sbb-text--bold` CSS class

- src/components/sbb-footer/sbb-footer.scss
- src/components/sbb-header/sbb-header.scss
> fix(sbb-footer, sbb-header): display divider to content on windows high contrast mode

- src/components.d.ts
- src/components/sbb-toggle-option/readme.md
- src/components/sbb-toggle-option/sbb-toggle-option.custom.d.ts
- src/components/sbb-toggle-option/sbb-toggle-option.e2e.ts
- src/components/sbb-toggle-option/sbb-toggle-option.events.ts
- src/components/sbb-toggle-option/sbb-toggle-option.spec.ts
- src/components/sbb-toggle-option/sbb-toggle-option.tsx
- src/components/sbb-toggle/sbb-toggle.spec.ts
- src/components/sbb-toggle/sbb-toggle.stories.js
- src/components/sbb-toggle/sbb-toggle.tsx
Refactors eventing around `sbb-toggle` and `sbb-toggle-option` to be more consistent on when an event is fired.
> refactor(sbb-toggle): optimize event handling

- src/components/sbb-header/readme.md
- src/components/sbb-header/sbb-header.scss
- src/components/sbb-logo/sbb-logo.scss
- src/storybook/pages/home/home--logged-in.stories.js
- src/storybook/pages/home/home.stories.js
Removed `--sbb-header-logo-height` CSS variable of `sbb-header` but introduced the `--sbb-logo-height` CSS var on the `sbb-logo`. With this change we can now style the logo through multiple levels in DOM.
> feat(sbb-header): style slotted link of sbb-logo

- src/components/sbb-dialog/readme.md
- src/components/sbb-dialog/sbb-dialog.scss
- src/components/sbb-menu/readme.md
- src/components/sbb-menu/sbb-menu.scss
- src/components/sbb-navigation-section/sbb-navigation-section.scss
- src/components/sbb-navigation/readme.md
- src/components/sbb-navigation/sbb-navigation.scss
- src/components/sbb-tooltip/readme.md
- src/components/sbb-tooltip/sbb-tooltip.scss
- src/global/styles/core/variables.scss
Provide the possibility to manually set the `z-index` property for all dialog based components. This is necessary since we use the `show()` method instead of the `showModal()` method (see more here #1368), which would otherwise place the dialog on top of everything else in the web page, regardless of the z-index of other elements.
> fix: provide CSS variables to set `z-index` for overlay components

- src/components/sbb-header/sbb-header.e2e.ts
- src/components/sbb-header/sbb-header.scss
- src/components/sbb-header/sbb-header.tsx
- src/components/sbb-menu/sbb-menu.scss
- src/components/sbb-menu/sbb-menu.tsx
- src/global/helpers/scroll.ts
Prevent the header from being hidden when the navigation is open/closed. Use the CSS `translateY` to perform the animation, instead of using `inset-block-start`.
> fix(sbb-header): prevent unwanted hiding and use transform for the animation

- src/components/sbb-header/sbb-header.scss
- src/components/sbb-header/sbb-header.tsx
- src/components/sbb-menu/sbb-menu.scss
- src/components/sbb-navigation/sbb-navigation.tsx
- src/global/helpers/scroll.ts
Simplifies and improves the mechanism for disabling page scroll.
- no visible "empty" scrollbar
- no "position: fixed" on the body
- no scroll references needed to reposition the page to the correct position
> refactor: improve scroll handling mechanism

- src/components/sbb-menu/sbb-menu.scss
- src/components/sbb-navigation-section/sbb-navigation-section.scss
- src/components/sbb-navigation/sbb-navigation.scss
Use dynamic viewport units to calculate the correct dimension for the `sbb-navigation` and the `sbb-navigation-section`. The bug is visible when the nav or the section goes in overflow on mobile.
> fix(sbb-navigation): set correct dimension on mobile

- src/components/sbb-form-error/sbb-form-error.spec.ts
- src/components/sbb-form-error/sbb-form-error.tsx
- src/components/sbb-form-field/readme.md
- src/components/sbb-form-field/sbb-form-field.e2e.ts
- src/components/sbb-form-field/sbb-form-field.scss
- src/components/sbb-form-field/sbb-form-field.spec.ts
- src/components/sbb-form-field/sbb-form-field.tsx
BREAKING CHANGE: It is now required to use a `<label>` to label an input via slot/element in a `<sbb-form-field>`.
> fix(sbb-form-field): always use label to link to input

- src/components/sbb-icon/sbb-icon.scss
- src/components/sbb-tab-group/sbb-tab-group.stories.js
Fix incorrect rendering on Safari when an `sbb-icon` is provided without a specified name property.
> fix(sbb-icon): empty icon on Safari

- src/components/sbb-menu/sbb-menu.scss
- src/global/helpers/position.spec.ts
- src/global/helpers/position.ts
Make sure that the positioned element is overflowing before repositioning it to where there is more space available.
> fix: stabilize positioning function

- src/components/sbb-menu/sbb-menu.tsx
With an open menu, if you scroll down the page there is a snap effect that moves the scroll to the focused trigger element
See [Review Guidelines](../REVIEW.md) for more information on what is checked during the review process.
> fix(sbb-menu): fixed the window snap on scrolling with an open menu

- src/components/sbb-icon/sbb-icon-request.ts
- src/components/sbb-timetable-row/sbb-timetable-row.helper.spec.ts
- src/components/sbb-timetable-row/sbb-timetable-row.helper.tsx
- src/components/sbb-timetable-row/sbb-timetable-row.spec.ts
- src/components/sbb-timetable-row/sbb-timetable-row.tsx
- src/global/interfaces/timetable-properties.ts
The `picto:`-namespace is now pointing to the new English named icons. If the old german named icons should be used, you can access them by using the namespace `picto-legacy:` (deprecated).
> refactor: migrate to new English named pictograms

- src/components/sbb-dialog/sbb-dialog.tsx
- src/components/sbb-menu/sbb-menu.tsx
- src/components/sbb-navigation/sbb-navigation.tsx
- src/components/sbb-tooltip/sbb-tooltip.e2e.ts
- src/components/sbb-tooltip/sbb-tooltip.tsx
- src/global/helpers/eventing/input-modality-detector.ts
- src/global/helpers/focus.ts
> fix(sbb-navigation): focus outline on the trigger element in Safari

- src/components.d.ts
- src/components/sbb-title/readme.md
- src/components/sbb-train/readme.md
- src/components/sbb-train/sbb-train.scss
- src/components/sbb-train/sbb-train.spec.ts
- src/components/sbb-train/sbb-train.stories.tsx
- src/components/sbb-train/sbb-train.tsx
> fix(sbb-train): improve accessibility by replacing `span` with heading tag

- src/global/helpers/eventing/action-element-handlers.ts
Previously it was not possible in Firefox for an action element with an internal anchor element (e.g. `<sbb-button href="...">` to be able to "click" it with an Enter press. This PR fixes this by switching from a `PointerEvent` to a `MouseEvent`.
> fix: enable pressing enter on action elements in Firefox

- src/components/sbb-datepicker/sbb-datepicker.e2e.ts
- src/components/sbb-form-field/readme.md
- src/components/sbb-form-field/sbb-form-field.e2e.ts
- src/components/sbb-form-field/sbb-form-field.spec.ts
- src/components/sbb-form-field/sbb-form-field.tsx
Currently `<sbb-form-field>` only links native form elements correctly via the `<label>` `for` attribute. This PR adds the functionality for custom form elements to be able to reference the `<label>` via `aria-labelledby` on the custom form element, which is done internally in the `<sbb-form-field>`.
> feat(sbb-form-field): reference label for custom form components

- src/components.d.ts
- src/components/sbb-autocomplete/sbb-autocomplete.tsx
- src/components/sbb-option/readme.md
- src/components/sbb-option/sbb-option.custom.d.ts
- src/components/sbb-option/sbb-option.e2e.ts
- src/components/sbb-option/sbb-option.tsx
- src/components/sbb-select/readme.md
- src/components/sbb-select/sbb-select.e2e.ts
- src/components/sbb-select/sbb-select.spec.ts
- src/components/sbb-select/sbb-select.stories.tsx
- src/components/sbb-select/sbb-select.tsx
This PR Closes #1827 
- the `@Watch('selected')` on the sbb-option has been removed to avoid infinite loops;
- the  `selectionChange` event is triggered only in user interaction cases;
- the `@Watch('value')` on sbb-select now looks on values on the sbb-options to display the correct label;
- a new public `@Method` has been added to fetch the displayValue.
> fix(sbb-select): select shows selected value in form field instead of the label

- src/components/sbb-button/sbb-button.stories.tsx
- src/global/helpers/eventing/action-element-handlers.ts
This PR Closes #1797 
- the submitter parameter has been removed when calling `requestSubmit`;
- a new story has been added with the `sbb-button` in a `form` tag.
> fix(sbb-button): remove submitter parameter

- src/components/sbb-icon/sbb-icon-request.ts
Our icon CDN is now available at https://icons.app.sbb.ch/.
> refactor: update icon cdn domain

- src/components/sbb-dialog/sbb-dialog.e2e.ts
- src/components/sbb-dialog/sbb-dialog.spec.ts
- src/components/sbb-dialog/sbb-dialog.tsx
This PR Closes #1834 
- Check event's composedPath to make sure click on overlays that overflow the dialog won't be counted as clicks on the backdrop
> fix(sbb-dialog): handle unwanted backdrop clicks on overlay components

- src/components/sbb-divider/readme.md
- src/components/sbb-navigation-section/readme.md
- src/components/sbb-navigation-section/sbb-navigation-section.scss
- src/components/sbb-navigation-section/sbb-navigation-section.spec.ts
- src/components/sbb-navigation-section/sbb-navigation-section.tsx
Closes #1934 
Has a one pixel shift of whole navigation section, but seems like designed in Figma
> fix(sbb-navigation-section): use divider instead of separation border

- src/components/sbb-card/sbb-card.scss
- src/global/styles/mixins/card.scss
> fix(sbb-card): allow placing tooltips inside non-interactive cards

- src/components/sbb-button/index.ts
- src/components/sbb-button/sbb-button.e2e.ts
- src/components/sbb-button/sbb-button.spec.ts
- src/components/sbb-button/sbb-button.stories.tsx
- src/components/sbb-button/sbb-button.tsx
- web-test-runner.config.js
> refactor(sbb-button): lit migration

- .storybook/preview-head.html
- src/components/sbb-alert/sbb-alert.stories.tsx
- src/components/sbb-breadcrumb-group/sbb-breadcrumb-group.stories.tsx
- src/components/sbb-breadcrumb/sbb-breadcrumb.stories.tsx
- src/components/sbb-button/sbb-button.stories.tsx
- src/components/sbb-card/sbb-card.stories.tsx
- src/components/sbb-header-action/sbb-header-action.stories.tsx
- src/components/sbb-link/sbb-link.stories.tsx
- src/components/sbb-menu-action/sbb-menu-action.stories.tsx
- src/components/sbb-navigation-action/sbb-navigation-action.stories.tsx
- src/components/sbb-skiplink-list/sbb-skiplink-list.stories.tsx
- src/components/sbb-teaser-hero/sbb-teaser-hero.stories.tsx
- src/components/sbb-teaser/sbb-teaser.stories.tsx
This PR adds a banner to the Storybook preview page, if viewed directly in the iframe. This is only visible in deployed versions.
> chore: mitigate phishing attacks

- src/components/sbb-breadcrumb/sbb-breadcrumb.spec.ts
- src/components/sbb-breadcrumb/sbb-breadcrumb.tsx
This PR fixes an issue with the rendering, when text or content is being added asynchronously after connecting the `<sbb-breadcrumb>` to the DOM.
> fix(sbb-breadcrumb): reliably detect text/content changes

- src/components.d.ts
- src/components/sbb-tab-group/readme.md
- src/components/sbb-tab-group/sbb-tab-group.custom.d.ts
- src/components/sbb-tab-group/sbb-tab-group.scss
- src/components/sbb-tab-group/sbb-tab-group.stories.tsx
- src/components/sbb-tab-group/sbb-tab-group.tsx
- src/components/sbb-tab-title/sbb-tab-title.scss
- src/components/sbb-tab-title/sbb-tab-title.spec.ts
- src/components/sbb-tab-title/sbb-tab-title.tsx
> feat(sbb-tab-group): tab titles redesign

- src/components/sbb-dialog/sbb-dialog.scss
- src/components/sbb-dialog/sbb-dialog.tsx
Fixes open/close method exit conditions and allows interactive elements under the header to be clicked.
> fix(sbb-dialog): open/close methods exit conditions

- src/components.d.ts
- src/components/sbb-loading-indicator/readme.md
- src/components/sbb-loading-indicator/sbb-loading-indicator.custom.d.ts
- src/components/sbb-loading-indicator/sbb-loading-indicator.scss
- src/components/sbb-loading-indicator/sbb-loading-indicator.spec.ts
- src/components/sbb-loading-indicator/sbb-loading-indicator.stories.tsx
- src/components/sbb-loading-indicator/sbb-loading-indicator.tsx
This PR adds two color variants to the default one.
- added smoke color and white color to loading indicator
> feat(sbb-loading): add indicator color variants

- src/components/sbb-image/index.ts
- src/components/sbb-image/sbb-image.e2e.ts
- src/components/sbb-image/sbb-image.stories.tsx
- src/components/sbb-image/sbb-image.tsx
> refactor(sbb-image): lit migration

- .github/workflows/continuous-integration.yml
- .storybook/main.ts
- vite.config.ts
- web-test-runner.config.js
Vite configuration always checks/merges the root configuration, so this PR excludes duplicate plugin configuration. Additionally, `.d.ts` files are only built for production builds. CI test runners are reduced in concurrency.
> build: optimize build configuration

- src/components/sbb-message/index.ts
- src/components/sbb-message/sbb-message.e2e.ts
- src/components/sbb-message/sbb-message.spec.ts
- src/components/sbb-message/sbb-message.stories.tsx
- src/components/sbb-message/sbb-message.tsx
> refactor(sbb-message): lit migration

- src/components/sbb-checkbox/sbb-checkbox.e2e.ts
- src/components/sbb-checkbox/sbb-checkbox.tsx
- src/components/sbb-radio-button/sbb-radio-button.e2e.ts
- src/components/sbb-radio-button/sbb-radio-button.tsx
- src/components/sbb-selection-panel/sbb-selection-panel.e2e.ts
> fix(sbb-selection-panel): remove wrongly announced expanded state for nested radios and checkboxes

- src/components/sbb-calendar/index.ts
- src/components/sbb-calendar/sbb-calendar.e2e.ts
- src/components/sbb-calendar/sbb-calendar.spec.ts
- src/components/sbb-calendar/sbb-calendar.stories.tsx
- src/components/sbb-calendar/sbb-calendar.tsx
> refactor(sbb-calendar): migrate component to lit

- src/components/sbb-menu/sbb-menu.tsx
Sets the focus on the first focusable inside the menu on open (mobile).
> fix(sbb-menu): menu action focus on mobile

- .prettierignore
- convenience/generate-component/boilerplate/component.e2e.ts
- convenience/generate-component/boilerplate/component.scss
- convenience/generate-component/boilerplate/component.spec.ts
- convenience/generate-component/boilerplate/component.stories.tsx
- convenience/generate-component/boilerplate/component.ts
- convenience/generate-component/boilerplate/component.tsx
- convenience/generate-component/index.mts
- package.json
- added templates and script for automatic component generation
> feat: add Lit blueprint

- src/components/sbb-journey-summary/sbb-journey-summary.spec.ts
- src/components/sbb-journey-summary/sbb-journey-summary.tsx
> fix(sbb-journey-summary): avoid list role for single entry lists

- src/components/datepicker/datepicker/datepicker.ts
Removed `async` / `await` inherited by mistake from Stencil version that allegedly caused tests to fail.
> refactor(sbb-datepicker): remove unnecessary code to stabilize tests

- src/components.d.ts
- src/components/sbb-checkbox/readme.md
- src/components/sbb-checkbox/sbb-checkbox.events.ts
- src/components/sbb-checkbox/sbb-checkbox.tsx
- src/components/sbb-radio-button-group/sbb-radio-button-group.e2e.ts
- src/components/sbb-radio-button-group/sbb-radio-button-group.tsx
- src/components/sbb-radio-button/readme.md
- src/components/sbb-radio-button/sbb-radio-button.events.ts
- src/components/sbb-radio-button/sbb-radio-button.tsx
- src/components/sbb-selection-panel/sbb-selection-panel.spec.ts
- src/components/sbb-selection-panel/sbb-selection-panel.tsx
> fix(sbb-radio-button-group): radio group state update

- src/components/datepicker/datepicker-next-day/datepicker-next-day.ts
- src/components/datepicker/datepicker-next-day/readme.md
- src/components/datepicker/datepicker-previous-day/datepicker-previous-day.ts
- src/components/datepicker/datepicker-previous-day/readme.md
- src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
- src/components/datepicker/datepicker-toggle/readme.md
Closes #2047 
Code for testing (in toggle stories):
```
const fn = () : void => {
const picker = document.createElement('sbb-datepicker');
const container = document.querySelector('#container');
container.append(picker);
};
const TestTemplate = ({negative, ...args}): JSX.Element => (
<div>
<sbb-form-field negative={negative} id='container'>
<input />
{StandaloneTemplate(null, args)}
</sbb-form-field>
<button onClick={() => fn()}>Click</button>
</div>
);
export const Test: StoryObj = {
render: TestTemplate,
argTypes: defaultArgTypes,
args: { ...defaultArgs },
};
```
Code for testing standalone case:
```
const fn = () : void => {
const picker = document.createElement('sbb-datepicker');
picker.setAttribute('id', 'datepicker');
picker.setAttribute('input', 'datepicker-input');
const container …
```
> fix: connect sbb-datepicker with related components when initialized

- DEVELOPER.md
- README.md
- TODOS.md
- docs/CICD.md
- docs/DEVELOP.md
- src/components/core/interfaces/link-button-properties.ts
- src/components/core/styles/global.scss
- src/components/core/testing/event-spy.ts
> chore: removed stencil references from docs

- src/components/core/dom/index.ts
- src/components/core/dom/strip-html.ts
- src/components/logo/logo.ts
- src/components/signet/signet.ts
Previous attempts to fix SSR failed due to various reasons. Now we just use property assignment with `.textContent`, which forces any text given to be interpreted as text. This avoid exploitation and simplifies the code.
> fix(sbb-logo,sbb-signet): solve SSR issue with text assignment

- src/components/vite.config.ts
This PR configures Vite to minify CSS in our build bundle. This should reduce the payload both for our package and our consumers.
> build: minify CSS in build bundle

- src/components/core/eventing/event-emitter.ts
This change allows us to check if an event was prevented. Additionally this PR enables SSR usage.
> refactor: change EventEmitter.emit to return the result of dispatchEvent

- src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
- src/components/logo/logo.ts
- src/components/signet/signet.ts
- tsconfig.json
Removed unused method on `sbb-datepicker-toggle` and imports in `sbb-logo` and `sbb-signet`.
> chore: remove unused import and code

- CODING_STANDARDS.md
> refactor: update coding standards

- src/components/toast/toast.scss
> feat: introduce css var for container position

- src/components/selection-panel/selection-panel.ts
Fix `data-state` on selection panels with no content.
> fix(sbb-selection-panel): fix data-state on selection panels with no content

- src/components/alert/alert-group/alert-group.scss
- src/components/alert/alert-group/alert-group.ts
- src/components/navigation/navigation-list/navigation-list.spec.ts
- src/components/navigation/navigation-list/navigation-list.ts
- src/components/tabs/tab-group/tab-group.scss
- src/components/tabs/tab-group/tab-group.ts
- src/components/timetable-travel-hints/timetable-travel-hints.ts
Avoid setting the class attribute on the host `setAttribute(this, 'class'...)` and prefer data attributes in order to prevent conflicts with pre-existing classes or classes that need to be toggled.
> fix: convert classes on host in data attributes

- src/components/autocomplete/autocomplete.ts
- src/components/checkbox/checkbox/checkbox.ts
- src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
- src/components/map-container/map-container.ts
- src/components/menu/menu/menu.ts
- src/components/navigation/navigation-section/navigation-section.ts
- src/components/navigation/navigation/navigation.ts
- src/components/notification/notification.ts
- src/components/select/select.ts
- src/components/selection-panel/selection-panel.ts
- src/components/tooltip/tooltip/tooltip.ts
With lit SSR, blocks in attributes that do not generate attributes seem to cause faulty rendering. E.g. skipping attributes or assigning wrong values.
> fix: move ref to the back of declarations

- ci/docs_generate.ts
- src/components/file-selector/readme.md
- src/components/form-field/form-field/readme.md
This PR Closes #2246
Now the docs-generate script uses the attribute name we specify in `@property({ attribute: ... })` instead of assuming it's the kebab-case version of the field name.
If a public property does not have an attribute, the column will be empty
> docs(readme): fix attribute name composition

- src/components/core/dom/platform.ts
- src/components/datepicker/datepicker/datepicker.e2e.ts
- src/components/select/select.ts
`<sbb-select>` causes a hydration error in Next.js. This PR implements a workaround by using the render logic of `@lit/react` to run our setup logic only after Next.js hydration or directly, if not in a Next.js environment.
> fix(sbb-select): adapt setup to work with Next.js hydration

- src/components/breadcrumb/breadcrumb-group/breadcrumb-group.stories.ts
- src/components/breadcrumb/breadcrumb/breadcrumb.stories.ts
- src/components/image/image.scss
- src/components/image/image.stories.ts
- src/components/image/image.ts
- src/components/selection-panel/selection-panel.stories.ts
- src/components/selection-panel/selection-panel.ts
Closes #2184
Fix for Chromatic issues:
- sbb-breadcrumb-group: 
- changed label from 'Breadcrumb' to 'Link' to avoid issue on smaller breakpoints;
- added `max-width` to handle expanded case in bigger breakpoints
- sbb-selection-panel:
- removed a duplicate emitter of did-* events when `disableAnimation` is true
- with a delay of 9 sec, it seems to correctly load (tested with 4 consecutive builds - can this be trusted?)
- sbb-image
- removed useless class in css
- adding a `max-width` seems to be solve the issue on Firefox
> fix: chromatic instability

- src/components/journey-header/journey-header.ts
This PR adds non breaking white space to the `sbb-journey-header`, to avoid text concatination (e.g. `from Zürich to Bern`, instead of `fromZürichtoBern`).
> fix(sbb-journey-header): add non breaking space for screen readers

- src/components/core/common-behaviors/slot-child-observer.ts
Our homepage is currently unstable and would crash on refresh, the problem only occurs on Mac and Chrome when there are a number of components on the page that depend on each other and are nested for more than two levels, it basically happens in the navigation with its various internal components (nav -> marker -> list -> action...). This is due to the new logic to do the children check with the `checkChildren` method implemented to optimise the SSR, by removing the `setTimeout` from the `firstUpdated` callback of the SlotChildObserver the problem is fixed.
> fix: remove setTimeout from SlotChildObserver

- src/react/core/create-component.ts
- Avoid setting element property if already set as attribute.
- Always set id as attribute to ensure id bindings
> fix: improve creation of react component

- src/components/notification/notification.e2e.ts
- src/components/notification/notification.ts
Currently if the notification node is removed directly after the `did-close` event is emitted, it causes an error in the React wrapper.
> fix(sbb-notification): delay removal of notification after closing

- src/components/teaser/__snapshots__/teaser.spec.snap.js
- src/components/teaser/readme.md
- src/components/teaser/teaser.e2e.ts
- src/components/teaser/teaser.scss
- src/components/teaser/teaser.spec.ts
- src/components/teaser/teaser.stories.ts
- src/components/teaser/teaser.ts
BREAKING CHANGE: The property `isStacked` has been removed in favor of `alignment`. Please see the documentation for further info. The `description` is not clamped to two lines anymore (responsibility of consumer). The slotted `image` has now a default width of `300px`. The slot, formerly named `description`, has been replaced by the unnamed slot. Support of nested `p` elements dropped (invalid html).
Closes #1897
This PR Closes #1897 
- sbb-chip has been included as optional element in the text part
- features 3 variants related to the text position: right-top, right-centered, bottom-left
- the user …
> feat(sbb-teaser): redesign

- src/components/core/styles/mixins/scrollbar.scss
Previously, when having a visible track on an outer scrollbar, the inner scrollbar inherits the track color.
With this change, all variables are always redefined to allow nested scrollbars.
> fix(scrollbar): fix track color in nested context

- scripts/chromatic-stories-generator.ts
- src/components/checkbox/checkbox/checkbox.ts
- src/components/notification/notification.stories.ts
- src/components/radio-button/radio-button/radio-button.ts
- src/components/selection-panel/readme.md
- src/components/selection-panel/selection-panel.e2e.ts
- src/components/selection-panel/selection-panel.scss
- src/components/selection-panel/selection-panel.stories.ts
- src/components/selection-panel/selection-panel.ts
This PR aims to solve the problems relative to the open/close events emitted by the `selection-panel`.
We have received no complaints, so I expect nobody is using them so far.
Might solve #2309 
- Converted the open/close animation from `css-transition` to `css-animation`. CSS animation provides a more consistent behavior and always emits `animationend` events.
- Refactored the code so that we have a single method that takes care of checking the state and to open/close the panel
- Should a panel that uses `force-open` emit events?
- Should a panel that uses `force-open` animate?
> refactor(selection-panel): improved open/close flow and animation

- src/components/alert/alert-group/alert-group.spec.ts
- src/components/alert/alert/__snapshots__/alert.spec.snap.js
- src/components/alert/alert/alert.e2e.ts
- src/components/alert/alert/alert.scss
- src/components/alert/alert/alert.spec.ts
- src/components/alert/alert/alert.stories.ts
- src/components/alert/alert/alert.ts
- src/components/alert/alert/readme.md
BREAKING CHANGE: renamed `willPresent` event to `willOpen` and `didPresent` to `didOpen`.
Closes #2389
> fix(sbb-alert): refactor animation to properly work in Safari

- src/components/form-field/form-field/form-field.scss
> fix(sbb-select): hide placeholder when using floating label in HCM

- src/components/clock/clock.scss
To overwrite color of seconds hand, use `--sbb-clock-seconds-hand-color` var on `sbb-clock`.
> feat(sbb-clock): introduce option to configure color of seconds hand

- package.json
- web-test-runner.config.js
Since we now have browser-specific snapshots,  the `test:snapshot` command has to run the update on each browser
> chore: update 'test:snapshot' command and dotReporter

- .github/workflows/continuous-integration.yml
This pr solves a deprecation warning on the new `is-pr-open` github action
> chore(github): update 'is-pr-open' action dep from v6 => v7

- src/components/navigation/common/navigation-action-common.ts
- src/components/navigation/common/navigation-action.scss
- src/components/navigation/navigation-button/readme.md
- src/components/navigation/navigation-link/readme.md
- src/components/navigation/navigation-marker/navigation-marker.e2e.ts
- src/components/navigation/navigation-marker/navigation-marker.stories.ts
- src/components/navigation/navigation-marker/navigation-marker.ts
- src/components/navigation/navigation-section/navigation-section.stories.ts
- src/components/navigation/navigation-section/navigation-section.ts
- src/components/navigation/navigation/navigation.e2e.ts
- src/components/navigation/navigation/navigation.stories.ts
- src/components/navigation/navigation/navigation.ts
- src/components/navigation/navigation/readme.md
- src/storybook/pages/home/home.common.ts
Closes #2338 
BREAKING CHANGE: The `<sbb-navigation-button>`/`<sbb-navigation-link>` `active` property has been removed. Add the CSS class `sbb-active` to the corresponsive button/link, to mark it as active.
> refactor(sbb-navigation): improve active handling and focus

- src/components/calendar/calendar.ts
- src/components/header/common/header-action-common.ts
- src/components/header/common/header-action.scss
- src/components/header/header-button/__snapshots__/header-button.spec.snap.js
- src/components/header/header-button/header-button.spec.ts
- src/components/header/header-link/__snapshots__/header-link.spec.snap.js
- src/components/header/header-link/header-link.spec.ts
- src/components/navigation/navigation-section/navigation-section.scss
- src/components/navigation/navigation-section/navigation-section.ts
This PR closes #2339 
Some components still use `isBreakpoint` in their code. Specifically:
- `sbb-calendar`: it's too complex to convert to a pure CSS approach (we delayed breakpoint-dependent code after hydration)
- `sbb-menu`: use `isBreakpoint` when opened (so no conflict with ssr)
- `navigation-section`: partially converted to CSS approach. The remaining part is not executed on init
> refactor(breakpoint): convert breakpoint-dependent code to pure css

- src/components/navigation/common/navigation-action-common.ts
- src/components/navigation/navigation-button/readme.md
- src/components/navigation/navigation-link/readme.md
Currently the reference set via connectedSection is reset to null, on upgrade/call of the constructor of the action web components (HTMLElement => SbbNavigationButtonElement/SbbNavigationLinkElement).
This is an unfortunate side effect of web components initialization.
> fix(sbb-navigation-section): ensure `sbb-active` initializes correctly

- .storybook/main.ts
- package.json
With Storybook 8.0 they started supporting the generation of `preview-stats.json` (used by turbosnap) with Vite.
We don't need the external plugin anymore 😄 
Ps. Chromatic will fail until we merge this fix
> chore: remove 'vite-plugin-turbosnap' dependency

- src/components/header/header/header.scss
Doesn't show the shadow if the header is not in `position: fixed`.
> fix(sbb-header): fix header shadow on keyboard navigation

- src/components/core/timetable/timetable-properties.ts
- src/components/timetable-row/timetable-row.sample-data.ts
- src/components/timetable-row/timetable-row.spec.ts
- src/components/timetable-row/timetable-row.ts
> refactor(timetable-row):  remove service product logic

- src/components/calendar/calendar.e2e.ts
- src/components/calendar/calendar.spec.ts
- src/components/calendar/calendar.stories.ts
- src/components/calendar/calendar.ts
- src/components/calendar/readme.md
- src/components/core/datetime/date-adapter.ts
- src/components/core/datetime/native-date-adapter.spec.ts
- src/components/core/datetime/native-date-adapter.ts
- src/components/core/interfaces/types.ts
- src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
- src/components/datepicker/datepicker/datepicker.ts
- tsconfig.json
This change allows us in the future to support different date libraries. However, this is only the implementation for the calendar. Datepicker will be done in a different PR.
The `SbbDatepicker` property `selectedDate` has been renamed to `selected`. This also applies to the attribute `selected-date`, which has been renamed to `selected`. Additionally the `DateAdapter` (and `NativeDateAdapter`) have been superficially refactored. An important change is that the month is now `1`-based, instead of `0`-based.
> refactor(sbb-calendar): implement initial support for other date libraries

- src/components/autocomplete/autocomplete.stories.ts
- src/components/autocomplete/readme.md
- src/components/button/mini-button/mini-button.stories.ts
- src/components/button/mini-button/readme.md
- src/components/datepicker/datepicker/datepicker.stories.ts
- src/components/dialog/dialog.stories.ts
- src/components/form-field/form-field-clear/__snapshots__/form-field-clear.spec.snap.js
- src/components/form-field/form-field-clear/form-field-clear.e2e.ts
- src/components/form-field/form-field-clear/form-field-clear.spec.ts
- src/components/form-field/form-field-clear/form-field-clear.stories.ts
- src/components/form-field/form-field-clear/readme.md
- src/components/form-field/form-field/__snapshots__/form-field.spec.snap.js
- src/components/form-field/form-field/form-field.e2e.ts
- src/components/form-field/form-field/form-field.spec.ts
- src/components/form-field/form-field/form-field.stories.ts
- src/components/form-field/form-field/form-field.ts
- src/components/form-field/form-field/readme.md
- src/components/option/optgroup/optgroup.stories.ts
- src/components/option/option/option.stories.ts
- src/components/select/readme.md
- src/components/select/select.stories.ts
- src/components/slider/readme.md
- src/components/slider/slider.stories.ts
- src/components/time-input/time-input.stories.ts
In order to support SSR we have to remove the label property. As replacement the `<label>` tag should be used.
BREAKING CHANGE: `label` property and attribute of `<sbb-form-field>` was removed. Use `<label>` tag inside `<sbb-form-field>` to provide the label information. E.g. `<sbb-form-field label="Example">...</sbb-form-field>` becomes `<sbb-form-field><label>Example</label>...</sbb-form-field>`
> fix(sbb-form-field): remove label property and attribute

- src/components/checkbox/checkbox/checkbox.stories.ts
- src/components/checkbox/checkbox/readme.md
- src/components/radio-button/radio-button/radio-button.stories.ts
- src/components/radio-button/radio-button/readme.md
This PR Closes #2498 
- add stories with bold label for sbb-checkbox and sbb-radio-button
> fix: stories with label bold for sbb-checkbox and sbb-radio-button

- src/components/checkbox/checkbox-group/checkbox-group.stories.ts
This PR Closes #2499 
- callbacks on change now set 'checked' and 'indeterminate' props instead of attributes
> docs(sbb-checkbox-group): set props instead of attributes in story

- src/components/core/styles/mixins/buttons.scss
- src/components/core/styles/typography.scss
- src/components/datepicker/datepicker-toggle/datepicker-toggle.scss
- src/components/form-field/form-field/form-field.e2e.ts
- src/components/form-field/form-field/form-field.scss
- src/components/form-field/form-field/form-field.stories.ts
- src/components/form-field/form-field/form-field.ts
- src/components/form-field/form-field/readme.md
- src/components/slider/slider.scss
Closes #2497
BREAKING CHANGE: The css var `--sbb-form-field-height` has been renamed to `--sbb-form-field-min-height`.
> feat(sbb-form-field): support the textarea inside the `<sbb-form-field>`

- src/components/datepicker/common/datepicker-button.ts
- src/components/datepicker/common/index.ts
- src/components/datepicker/datepicker-next-day/datepicker-next-day.ts
- src/components/datepicker/datepicker-next-day/readme.md
- src/components/datepicker/datepicker-previous-day/datepicker-previous-day.ts
- src/components/datepicker/datepicker-previous-day/readme.md
- src/components/datepicker/datepicker/datepicker.ts
- src/components/datepicker/index.ts
This PR Closes #2531 
- a new base class named `SbbDatepickerButton` has been created to include all the shared code between the `SbbDatepickerPreviousDay` and the `SbbDatepickerNextDay`
> refactor: base element for datepicker buttons

- src/components/core/styles/core/functions.scss
- src/components/core/styles/core/mediaqueries.scss
- src/components/vite.config.ts
- tools/vite/copy-sass.ts
- tools/vite/index.ts
This allows our .scss files to be consumed without depending on the `@sbb-esta/lyne-design-tokens` package.
Closes #2513
> fix(sass): inline external .scss files during build

- src/components/dialog/dialog-actions/readme.md
- src/components/dialog/dialog/readme.md
The current examples show `<sbb-dialog-action>` (singular) which is wrong. It should be plural instead.
This PR Closes # (no issue opened)
- change the examples to be `<sbb-dialog-actions>` (plural)
Why is this even important? If you use lyne with Angular (maybe/probably others too), currently you won't get Intellisense or any other indication that there's no component called `<sbb-dialog-action>` and it simply won't show up.
> docs(sbb-dialog-actions): change examples to be in plural form

- src/components/calendar/calendar.ts
- src/components/clock/clock.ts
- src/components/core/datetime.ts
- src/components/datepicker/datepicker-next-day/datepicker-next-day.ts
- src/components/datepicker/datepicker-previous-day/datepicker-previous-day.ts
- src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
- src/components/datepicker/datepicker/datepicker.ts
- src/components/journey-summary/journey-summary.ts
- src/components/pearl-chain-time/pearl-chain-time.ts
- src/components/pearl-chain/pearl-chain.ts
- src/components/timetable-row/timetable-row.ts
- src/components/vite.config.ts
- tools/vite/index.ts
- tools/vite/verify-entry-points.ts
This PR fixes the remaining missed import paths that were not adapted. It additionally adds a vite plugin check, to ensure the build would break, if an illegal import was used.
> fix: update import paths missed in the migration

- src/components/action-group/action-group.spec.ts
- src/components/action-group/action-group.stories.ts
- src/components/action-group/readme.md
This PR Closes #2583 
- add stories with button-size='s' in action-group stories
> docs(sbb-action-group): add button-size small

- .storybook/preview.ts
- scripts/chromatic-stories-generator.ts
- scripts/migrate-ssr-e2e.ts
- scripts/migrate-toggle-data-entry.ts
Our chromatic story generation got disabled in the eslint migration. This PR re-enables it.
> build: re-enable chromatic stories

- docs/GETTING_STARTED.md
- package.json
- src/components/breadcrumb/breadcrumb-group/breadcrumb-group.scss
- src/components/core/styles/mixins/font-face.scss
- src/components/core/styles/mixins/panel.scss
- src/components/core/styles/mixins/typo.scss
- src/components/core/styles/typography.scss
- src/components/form-field/form-field/form-field.scss
- src/components/loading-indicator/loading-indicator.stories.ts
- src/components/menu/menu-link/menu-link.stories.ts
- src/components/menu/menu/menu.stories.ts
- src/components/pearl-chain-vertical/pearl-chain-vertical.stories.ts
- src/components/skiplink-list/skiplink-list.stories.ts
- src/components/tabs/tab-group/tab-group.stories.ts
- src/storybook/styles/list/list.stories.ts
- src/storybook/styles/typography/readme.md
- yarn.lock
Closes #2614 
BREAKING CHANGE: replaced Roman, Bold, and Light font-face variants with the single "SBB" font.
Using CSS `font-weight` property automatically selects the correct font family.
Migration guide:
- Replace `font-family: "SBBWeb Roman", ...` with `font-family: "SBB", ...`  and use `font-weight: normal` (potentially not necessary as `normal` is the default).
- Replace `font-family: "SBBWeb Bold", ...` with `font-family: "SBB", ...` and use `font-weight: bold` or CSS class `sbb-text--bold`.
- Replace `font-family: "SBBWeb Light", ...` with `font-family: "SBB", ...` and use `font-weight: 300`.
- Replace CSS variable `--sbb-typo-type-face-sbb-roman` with `--sbb-typo-font-family` and use `font-weight: normal` (potentially not necessary as `normal` is the default).
- Replace CSS …
> feat: reduce font-faces to single SBB variant

- src/components/container/container/container.scss
- src/components/core/styles/mixins/helpers.scss
- src/components/tabs/tab-group/tab-group.scss
- src/components/tabs/tab-group/tab-group.stories.ts
> fix(sbb-tab-group): avoid unwanted margin block spaces

- src/components/vite.config.ts
- tools/vite/generate-root-entry-point.ts
- tools/vite/index.ts
This feature allows using `import '@sbb-esta/lyne-components'`, which will import all components and add them to `globalThis`, but will not provide an export. This is useful for SSR or for providing examples/reproductions and wanting to load all components.
> feat: add root entry point with global component registration

- src/components/vite.config.ts
This should allow the css files to be imported as-is from vite, without having to add additional conditions.
> feat: add default entries for style exports in package.json

- tools/web-test-runner/vite-plugin.js
- web-test-runner.config.js
By using streaming in our vite to web-test-runner proxy, we can improve the concurrency capabilities of running tests.
> build: improve test runner concurrency

- src/elements-experimental/vite.config.ts
- src/elements/vite.config.ts
This PR adds a configuration to mangle private properties in prod builds. Currently this saves about 40kB (of about 800kB total).
This technically also prevents consumers from using private API, as it will be reduced to a single letter usually.
Personal opinion: While this does not have a huge impact, I still feel like we should try to optimize where possible. But I would like to hear your opinions on this @jeripeierSBB, @TomMenga.
> build: mangle private properties in prod build to reduce size

- package.json
- yarn.lock
Solves: 
- Tests freeze when an assertion fails
The problem was introduced with the update of the `@web/dev-server-core` package (dependency of `@web/test-runner`).
Specifically, the [faulty change](https://github.com/modernweb-dev/web/commit/feb0c72815bd9f803ef61eab0819c9b6fd4f05d8#diff-f245ba1e1d0627b81dcc9602856b458d1b36f15d8121126f1cfce7f2c96e991f) is the use of `structuredClone`. 
The `stable` function is called before reporting the test suite result which contains a reference to the element on which the assertion failed (in our case, the web component, which cannot be cloned).
TODO: Open an issue in https://github.com/modernweb-dev/web
> test: fix freeze on assert fail

- src/elements/core/styles/mixins/buttons.scss
- src/elements/datepicker/datepicker-toggle/datepicker-toggle.scss
The two datepicker buttons are not displayed correctly in the disabled and focused state in both Firefox and Safari; perhaps this was not detected before due to browsers being removed from Chromatic.
A similar fix was made to the popover-trigger and is also available in the new autocomplete-grid.
> style: fix mini-button mixin

- src/elements/notification/notification.scss
This PR addresses a specific requirement from sbb.ch. However, we do not want to generally provide this as a feature, so we do not provide documentation for this.
The property is named `--sbb-notification-icon-size` and can be set to `0` to hide the icon.
> refactor(sbb-notification): add CSS property to define icon size

- src/elements/core/mixins/hydration-mixin.ts
This PR slightly changes how we handled slotchange events during hydration. Previously we would stop slotchange events during hydration and re-dispatch them afterwards. However, it seems that during true page load with server side rendering, slotchange events are not dispatched at all. So we changed the logic to just generally suppress slotchange events during hydration and manually dispatch a slotchange event, for any slot having content assigned, after the hydration is finished.
> fix: ensure slotchange events are handled correctly in hydration

- src/elements/button/common/button-common.ts
- src/elements/button/mini-button/mini-button.ts
- src/elements/checkbox/checkbox-group/checkbox-group.ts
- src/elements/checkbox/checkbox-panel/checkbox-panel.ts
- src/elements/checkbox/checkbox/checkbox.ts
- src/elements/core/decorators.ts
- src/elements/core/decorators/host-attributes.ts
- src/elements/core/decorators/slot-state.ts
- src/elements/file-selector/file-selector.ts
- src/elements/form-field/form-field/form-field.ts
- src/elements/link-list/link-list.ts
- src/elements/link/common/link-common.ts
- src/elements/navigation/navigation-list/navigation-list.ts
- src/elements/navigation/navigation-section/navigation-section.ts
- src/elements/notification/notification.ts
- src/elements/option/option/option.ts
- src/elements/radio-button/radio-button-group/radio-button-group.ts
- src/elements/radio-button/radio-button-panel/radio-button-panel.ts
- src/elements/radio-button/radio-button/radio-button.ts
- src/elements/selection-expansion-panel/selection-expansion-panel.ts
- src/elements/skiplink-list/skiplink-list.ts
- src/elements/status/status.ts
- src/elements/tabs/tab-label/tab-label.ts
- src/elements/tag/tag/tag.ts
- src/elements/teaser/teaser.ts
- src/elements/toast/toast.ts
- src/elements/toggle-check/toggle-check.ts
- src/elements/toggle/toggle-option/toggle-option.ts
This PR replaces the constructor usage of `SbbSlotStateController` with the decorator `slotChange`, which applies the `SbbSlotStateController` internally.
> refactor: replace isolated `SbbSlotStateController` usage with decorator

- src/elements/datepicker/datepicker-toggle/datepicker-toggle.visual.spec.ts
- src/elements/navigation/navigation-button/navigation-button.visual.spec.ts
- src/elements/navigation/navigation-link/navigation-link.visual.spec.ts
- src/elements/navigation/navigation-section/navigation-section.visual.spec.ts
- src/elements/navigation/navigation/navigation.visual.spec.ts
Contains:
- sbb-navigation
- sbb-navigation-section
- sbb-navigation-button
- sbb-navigation-link
- ~~sbb-navigation-list~~ (included in navigation / navigation-section)
- ~~sbb-navigation-marker~~ (included in navigation / navigation-section)
> test(sbb-navigation): add visual spec

- src/elements/title/__snapshots__/title.snapshot.spec.snap.js
- src/elements/title/title.snapshot.spec.ts
- src/elements/title/title.visual.spec.ts
not sure if it's worth testing all viewport sizes
> test(sbb-title): implement visual regression tests

- src/elements/popover/popover/popover.ssr.spec.ts
- src/elements/popover/popover/popover.ts
> fix(sbb-popover): prevent matchMedia call before hydration

- src/elements/calendar/calendar.ts
- src/elements/core/datetime/date-adapter.ts
- src/elements/core/datetime/native-date-adapter.ts
- src/elements/datepicker/common/datepicker-button.ts
- src/elements/datepicker/datepicker-next-day/datepicker-next-day.ts
- src/elements/datepicker/datepicker-next-day/readme.md
- src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.ts
- src/elements/datepicker/datepicker-previous-day/readme.md
- src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
- src/elements/datepicker/datepicker/datepicker.spec.ts
- src/elements/datepicker/datepicker/datepicker.ssr.spec.ts
- src/elements/datepicker/datepicker/datepicker.stories.ts
- src/elements/datepicker/datepicker/datepicker.ts
- src/elements/datepicker/datepicker/readme.md
This change adds support for the `DateAdapter` to all datepicker related components (`<sbb-datepicker>`, `<sbb-datepicker-toggle>`, `<sbb-datepicker-previous-day>` and `<sbb-datepicker-next-day>`).
Closes #2865, closes #1915
Partially supersedes #2244 (Thank you @DavideMininni-Fincons for the initial work!)
> feat(sbb-datepicker): add support for `DateAdapter`

- src/elements/stepper/stepper/stepper.ts
- src/elements/tabs/tab-group/tab-group.ts
- src/elements/toast/toast.ts
In components that have a `slotchange` event handler for an initialization and no fallback, we need to use the `SbbHydrationMixin` to ensure the `slotchange` event is fired even with declarative Shadow DOM.
> fix(various): ensure slotchange event is handled properly in hydration

- src/elements/teaser/teaser.visual.spec.ts
Note: 
the two 'after' alignments are cropped at lower breakpoints (eg. [storybook](https://lyne-storybook.app.sbb.ch/?path=/story/elements-sbb-teaser-sbb-teaser--after-centered&globals=viewport:micro)), so i decided to create a custom combinations of breakpoints/alignments.
> test(sbb-teaser): add visual tests

- src/elements/alert/alert-group/__snapshots__/alert-group.snapshot.spec.snap.js
- src/elements/alert/alert-group/alert-group.spec.ts
- src/elements/alert/alert-group/alert-group.ts
- src/elements/alert/alert/__snapshots__/alert.snapshot.spec.snap.js
- src/elements/alert/alert/alert.scss
- src/elements/alert/alert/alert.spec.ts
- src/elements/alert/alert/alert.stories.ts
- src/elements/alert/alert/alert.ts
- src/elements/alert/alert/readme.md
- src/elements/notification/notification.ts
- src/elements/notification/readme.md
This PR Closes #2745
- Add fade-out animation for `sbb-alert`
- `sbb-alert` `[animation]` default value changed from `open => all`
BREAKING CHANGE: `animation` property default value changes from `open` to `all` (the close animation is enabled by default)
> feat(sbb-alert): add close fade-out animation

- src/elements/clock/clock.ts
Previously `_startClock` would not finish, as the awaited Promise would not resolve. This prevented other internal methods from completing.
> fix(sbb-clock): fix internal await to actually finish

- src/elements/core/testing.ts
- src/elements/core/testing/wait-for-event.ts
- src/elements/menu/menu/menu.ts
- src/elements/navigation/navigation/navigation.spec.ts
- src/elements/navigation/navigation/navigation.ts
- src/elements/overlay/overlay-base-element.ts
Currently if an overlay element is removed from the DOM before its `animationend` event is called, the page is stuck with disabled scrolling. To prevent this, we re-enable the scrolling additionally in the `disconnectedCallback`.
Closes #2967
> fix(various): re-enable scrolling when disconnecting the component before animationend

- src/elements/icon/icon.ts
> feat(sbb-icon): provide compatibility with sbb-angular

- src/elements/autocomplete-grid/autocomplete-grid/readme.md
- fixes some storybook links in autocomplete-grid readme file.
> docs(sbb-autocomplete-grid): fix urls in readme.md

- src/elements/container/container/__snapshots__/container.snapshot.spec.snap.js
- src/elements/container/container/container.scss
- src/elements/container/container/container.snapshot.spec.ts
- src/elements/container/container/container.stories.ts
- src/elements/container/container/container.ts
- src/elements/container/container/container.visual.spec.ts
- src/elements/container/container/readme.md
- src/elements/core/images.ts
- src/elements/overlay/__snapshots__/overlay.snapshot.spec.snap.js
This PR Closes #2963 
-
TODO: fix visual spec not loading image
> feat(sbb-container): support for background image

- src/elements/core/i18n/i18n.ts
- src/elements/flip-card/flip-card-summary/__snapshots__/flip-card-summary.snapshot.spec.snap.js
- src/elements/flip-card/flip-card-summary/flip-card-summary.scss
- src/elements/flip-card/flip-card-summary/flip-card-summary.snapshot.spec.ts
- src/elements/flip-card/flip-card-summary/flip-card-summary.stories.ts
- src/elements/flip-card/flip-card-summary/flip-card-summary.visual.spec.ts
- src/elements/flip-card/flip-card-summary/readme.md
- src/elements/flip-card/flip-card/__snapshots__/flip-card.snapshot.spec.snap.js
- src/elements/flip-card/flip-card/flip-card.scss
- src/elements/flip-card/flip-card/flip-card.snapshot.spec.ts
- src/elements/flip-card/flip-card/flip-card.spec.ts
- src/elements/flip-card/flip-card/flip-card.ssr.spec.ts
- src/elements/flip-card/flip-card/flip-card.stories.ts
- src/elements/flip-card/flip-card/flip-card.ts
- src/elements/flip-card/flip-card/flip-card.visual.spec.ts
- src/elements/flip-card/flip-card/readme.md
> fix(sbb-flip-card): fix accessibility issues

- src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.stories.ts
- src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.visual.spec.ts
- src/elements/autocomplete-grid/autocomplete-grid/readme.md
- src/elements/autocomplete/autocomplete.stories.ts
- src/elements/autocomplete/autocomplete.visual.spec.ts
- src/elements/autocomplete/readme.md
- src/visual-regression-app/src/components/test-case/test-title-chip-list/test-title-chip-list.ts
This PR Closes #2768 
- introduce examples for sbb-autocomplete in form-field size=s
> feat(sbb-autocomplete): introduce size s

- src/elements/core/styles/core.scss
- src/elements/time-input/readme.md
- src/elements/time-input/time-input.stories.ts
- src/elements/time-input/time-input.visual.spec.ts
This PR Closes #2769 
Most of the task was accomplished by the form field. 
The only doubt I have is on a CSS rule in `core.scss` that sets the max-width for time inputs. 
The value seems arbitrary and I could not find it in Figma. Might be that we need to tune it when sizing 's'
@jeripeierSBB Perhaps you know something more?
> feat(sbb-time-input): add size 's'

- src/elements/core/styles/mixins/table.scss
- src/elements/core/styles/table.scss
- src/storybook/styles/table/readme.md
- src/storybook/styles/table/table.stories.ts
- src/storybook/styles/table/table.visual.spec.ts
DSO KIS needs a smaller table style (XS).
- added new style (XS) for tables
> feat(table): introduce table size xs

- src/elements/radio-button/radio-button-group/radio-button-group.spec.ts
- src/elements/radio-button/radio-button-group/radio-button-group.ts
> fix(sbb-radio-group): disable focus when disabling radio

- vite.config.ts
We will need to investigate the necessary changes in the future: https://sass-lang.com/documentation/breaking-changes/legacy-js-api/
> build: silence sass deprecation warning

- src/elements-experimental/journey-summary/journey-summary.stories.ts
- src/elements-experimental/journey-summary/journey-summary.ts
- src/elements-experimental/journey-summary/journey-summary.visual.spec.ts
- src/elements-experimental/journey-summary/readme.md
- a11y-footpath attribute added for displaying wheelchair icon
> feat(sbb-journey-summary): provide a11y footpath property

- .stylelintrc.json
- src/elements/autocomplete/autocomplete-base-element.scss
- src/elements/button/common/button-common.scss
- src/elements/checkbox/checkbox/checkbox.scss
- src/elements/core/styles/core/functions.scss
- src/elements/core/styles/mixins/helpers.scss
- src/elements/core/styles/mixins/lists.scss
- src/elements/core/styles/mixins/scrollbar.scss
- src/elements/core/styles/mixins/table.scss
- src/elements/core/styles/normalize.scss
- src/elements/loading-indicator/loading-indicator.scss
- src/elements/notification/notification.scss
- src/elements/select/select.scss
- src/storybook/pages/home/home.scss
SCSS `/*` comments are getting compiled into CSS. Having such comments in mixins generates a lot of redundant output. With the stylelint rule, we can avoid it.
> build: avoid compiling CSS comments

- src/elements/radio-button/radio-button-group/radio-button-group.ts
- src/elements/selection-expansion-panel/selection-expansion-panel.spec.ts
> fix(sbb-radio-group): avoid focusing disabled radios

- src/elements/teaser/readme.md
- src/elements/teaser/teaser.scss
- src/elements/teaser/teaser.stories.ts
- src/elements/teaser/teaser.visual.spec.ts
> fix(sbb-teaser): allow teaser usage in flexible layouts

- tools/web-test-runner/index.ts
- tools/web-test-runner/preload-fonts.ts
- tools/web-test-runner/preload-icons.ts
- web-test-runner.config.ts
Similar to what we already do, this PR downloads the fonts before test runs and inlines them in the initial HTML. This avoids flakey font resolution in tests.
> build: inline fonts during tests

- src/elements/loading-indicator/loading-indicator.scss
NOTE: where does the original `-3em` value come from?
> fix(sbb-loading-indicator): center component into his box

- src/elements/header/common/header-action.scss
- src/elements/header/header-button/header-button.stories.ts
- src/elements/header/header-button/header-button.visual.spec.ts
- src/elements/header/header-button/readme.md
- src/elements/header/header-link/header-link.stories.ts
- src/elements/header/header-link/header-link.visual.spec.ts
- src/elements/header/header-link/readme.md
- src/elements/header/header/header.stories.ts
- src/elements/header/header/readme.md
> feat(sbb-header): introduce active state

- .github/workflows/continuous-integration-secure.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/release-please.yml
Fixes usage of the tag parameter, which only expects the image tag and not the full path (contrary to Docker/Buildah).
> build: fix slim container image build

- src/elements/option/option/option-base-element.ts
BREAKING CHANGE: removed `active` property from `sbb-option` and `sbb-autocomplete-grid-option`
> fix(sbb-option,sbb-autocomplete-grid-option): remove deprecated `active` property

- src/elements/datepicker/common/datepicker-button.ts
- src/elements/form-field/form-field/form-field.ts
- src/elements/form-field/form-field/readme.md
BREAKING CHANGE: The `getInputElement()` method of the `sbb-form-field` has been removed. Use `inputElement` property as alternative.
> fix(sbb-form-field): remove deprecated `getInputElement()` method

- src/elements/alert/alert-group/alert-group.spec.ts
- src/elements/alert/alert-group/alert-group.stories.ts
- src/elements/alert/alert-group/alert-group.ts
- src/elements/alert/alert-group/alert-group.visual.spec.ts
- src/elements/alert/alert-group/readme.md
- src/elements/alert/alert/alert.spec.ts
- src/elements/alert/alert/alert.stories.ts
- src/elements/alert/alert/alert.ts
- src/elements/alert/alert/readme.md
- src/elements/notification/notification.ts
BREAKING CHANGE: The deprecated `dismissalRequested` event and requestDismissal() method of `sbb-alert` have been removed. The `sbb-alert` handles its closing and DOM removal on his own. If the closing should be prevented, the willClose event can be canceled. The `didDismissAlert` of the `sbb-alert-group` has been removed. As alternative, consumers can listen to the `didClose` event of an `sbb-alert`.
> fix(sbb-alert, sbb-alert-group): remove dismissal event and method

- .github/workflows/codeql-analysis.yml
I noticed this warning in another PR of mine
https://github.com/sbb-design-systems/lyne-components/actions/runs/11976958791
Code QL v2 will be deprecated in December 2024. 
https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
> build: update codeql action from v2 to v3

- src/elements/checkbox/checkbox-panel/readme.md
- src/elements/checkbox/checkbox/readme.md
- src/elements/checkbox/common/checkbox-common.spec.ts
- src/elements/core/mixins/form-associated-checkbox-mixin.ts
- src/elements/core/mixins/form-associated-radio-button-mixin.ts
- src/elements/file-selector/common/file-selector-common.spec.ts
- src/elements/file-selector/common/file-selector-common.ts
- src/elements/file-selector/file-selector-dropzone/readme.md
- src/elements/file-selector/file-selector/readme.md
- src/elements/radio-button/common/radio-button-common.spec.ts
- src/elements/radio-button/radio-button-panel/readme.md
- src/elements/radio-button/radio-button/readme.md
- src/elements/select/readme.md
- src/elements/select/select.spec.ts
- src/elements/select/select.ts
- src/elements/slider/readme.md
- src/elements/slider/slider.spec.ts
- src/elements/slider/slider.ts
- src/elements/toggle-check/readme.md
> fix: fix type of form associated controls

- src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
- src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.ts
- src/elements/autocomplete/autocomplete.spec.ts
- src/elements/autocomplete/autocomplete.ts
> fix(sbb-autocomplete, sbb-autocomplete-grid): avoid form submission on enter press

- .storybook/preview-head.html
- src/elements/header/header/__snapshots__/header.snapshot.spec.snap.js
- src/elements/header/header/header.scss
- src/elements/header/header/header.snapshot.spec.ts
- src/elements/header/header/header.stories.ts
- src/elements/header/header/header.ts
- src/elements/header/header/header.visual.spec.ts
- src/elements/header/header/readme.md
- src/elements/map-container/map-container.stories.ts
- src/elements/map-container/map-container.visual.spec.ts
- src/storybook/pages/home/home--logged-in.stories.ts
- src/storybook/pages/home/home.stories.ts
- src/visual-regression-app/src/components/test-case/test-case.ts
This PR Closes #3093 
BREAKING CHANGE: removed the `logo` slot and the default `sbb-logo` from the `sbb-header`. 
Alternatively, add the `sbb-header-logo` **class** to the logo and use the default slot. 
TODO:
- Discuss the use case we have in the "Customizing" section of the readme ✅
> refactor(sbb-header): removed 'logo' slot

- src/elements/alert/alert-group/__snapshots__/alert-group.snapshot.spec.snap.js
- src/elements/alert/alert-group/alert-group.snapshot.spec.ts
- src/elements/alert/alert-group/alert-group.spec.ts
- src/elements/alert/alert-group/alert-group.ssr.spec.ts
- src/elements/alert/alert-group/alert-group.stories.ts
- src/elements/alert/alert-group/alert-group.visual.spec.ts
- src/elements/alert/alert-group/readme.md
- src/elements/alert/alert/__snapshots__/alert.snapshot.spec.snap.js
- src/elements/alert/alert/alert.snapshot.spec.ts
- src/elements/alert/alert/alert.stories.ts
- src/elements/alert/alert/alert.ts
- src/elements/alert/alert/alert.visual.spec.ts
- src/elements/alert/alert/readme.md
- src/elements/core/i18n/i18n.ts
- src/elements/lead-container/lead-container.stories.ts
- src/elements/lead-container/lead-container.visual.spec.ts
- src/elements/lead-container/readme.md
- src/storybook/pages/home/home.ts
BREAKING CHANGE: The link properties (`linkContent`, `href`, `target`, `rel`, `accessibilityLabel`) of the `sbb-alert` have been removed. Consumers have to slot a `<sbb-link>` into the unnamed content slot.
> refactor(sbb-alert): remove sbb-link from shadow DOM

- src/elements/form-field/form-field/form-field.spec.ts
- src/elements/form-field/form-field/form-field.ts
> fix(sbb-form-field): update floating label on programmatic changes

- src/elements/core/mixins/form-associated-mixin.ts
- src/elements/radio-button/common/radio-button-common.spec.ts
- src/elements/radio-button/radio-button-panel/radio-button-panel.ts
During the generation of the Angular classes in the new repo, the SbbFormAssociatedMixinType is marked with `customElement: true`, which breaks some logic.
> fix: fix mixin due to wrong manifest generation

- tools/manifest/custom-elements-manifest.config.js
The datepicker and the calendar components use generic type parameter to allow custom implementation of Date, eg.
```
export class SbbDatepickerElement<T = Date> {
private _min?: T | null;
// and so on
}
```
This needs to be taken in account in Angular classes generation, so a new param has been added to the manifest during its generation, eg.
```
{
"kind": "javascript-module",
"path": "datepicker/datepicker.js",
"declarations": [
{
"kind": "class",
"description": "Combined with a native input, it displays the input's value as a formatted date.",
"name": "SbbDatepickerElement",
"members": [],
"events": [],
"attributes": [],
"superclass": {},
"classGenerics": "T = Date",        <--------------------------------- new property
"tagName": "sbb-datepicker",
"customElement": true
}
],
exports: …
```
> feat: add class generic type param in manifest

- src/elements/message/message.scss
- src/elements/message/message.visual.spec.ts
> fix(sbb-message): fix image alignment

- src/elements/calendar/calendar.spec.ts
- src/elements/calendar/calendar.ts
- src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
- src/elements/navigation/common/navigation-action-common.ts
- src/elements/slider/slider.ts
- src/elements/stepper/step/step.ts
- src/elements/stepper/stepper/readme.md
- src/elements/stepper/stepper/stepper.ts
- src/elements/tag/tag-group/tag-group.ts
- src/elements/time-input/time-input.ts
Changes are related to Angular wrapper's classes generation.
- `sbb-calendar`: normalized null / undefined types for getters and setters; needs some fix for the `sbb-datepicker-toggle`
- `sbb-navigation-action-common`: updated mixin type
- `sbb-slider`: normalized type
- `sbb-stepper`: some minor fix to normalize null values, which are already considered in the existing logic but not in typings
- `sbb-tag-group`: normalized type
- `sbb-time-input`: add null as type as in the getter
- properties of `SbbStepValidateEventDetails` are now nullable and they are not optional anymore
> fix: improve null/undefined type handling for Angular wrapper

- src/elements/core/styles/mixins/lists.scss
Before, in the icon list there was an unintentional padding which this PR removes.
> fix: remove leading inline padding from icon list

- src/elements/autocomplete/autocomplete-base-element.ts
- src/elements/core/eventing/forward-event.ts
- src/elements/datepicker/datepicker/datepicker.ts
- src/elements/dialog/dialog-content/dialog-content.ts
- src/elements/dialog/dialog/dialog.spec.ts
- src/elements/dialog/dialog/dialog.ts
- src/elements/file-selector/common/file-selector-common.ts
- src/elements/map-container/map-container.spec.ts
- src/elements/map-container/map-container.ts
- src/elements/menu/menu/menu.spec.ts
- src/elements/menu/menu/menu.ts
- src/elements/navigation/navigation/navigation.spec.ts
- src/elements/navigation/navigation/navigation.ts
- src/elements/notification/notification.ts
- src/elements/overlay/overlay.spec.ts
- src/elements/overlay/overlay.ts
- src/elements/popover/popover/popover.ts
- src/elements/select/select.ts
- src/elements/slider/slider.ts
- src/elements/time-input/time-input.ts
> fix: handle scroll events in custom scroll contexts

- src/elements/dialog/dialog/__snapshots__/dialog.snapshot.spec.snap.js
- src/elements/dialog/dialog/dialog.scss
- src/elements/dialog/dialog/dialog.stories.ts
- src/elements/dialog/dialog/dialog.ts
- src/elements/dialog/dialog/dialog.visual.spec.ts
- src/elements/dialog/dialog/readme.md
> feat(sbb-dialog): introduce `backdrop` property to control backdrop density

- web-test-runner.config.ts
This improves usage in test debugging, as the body element is no longer cluttered with template tags.
> build: move icon templates into dedicated div

- src/elements/core/datetime/date-adapter.ts
- src/elements/core/datetime/native-date-adapter.ts
- src/elements/datepicker/common.ts
- src/elements/datepicker/common/datepicker-association-controllers.ts
- src/elements/datepicker/common/datepicker-button.ts
- src/elements/datepicker/datepicker-next-day/datepicker-next-day.spec.ts
- src/elements/datepicker/datepicker-next-day/readme.md
- src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.spec.ts
- src/elements/datepicker/datepicker-previous-day/readme.md
- src/elements/datepicker/datepicker-toggle/datepicker-toggle.spec.ts
- src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
- src/elements/datepicker/datepicker-toggle/readme.md
- src/elements/datepicker/datepicker/__snapshots__/datepicker.snapshot.spec.snap.js
- src/elements/datepicker/datepicker/datepicker.snapshot.spec.ts
- src/elements/datepicker/datepicker/datepicker.ts
- src/elements/datepicker/datepicker/readme.md
> fix: handle datepicker association reliably

- src/elements/container/container/container.scss
- src/elements/container/container/container.stories.ts
- src/elements/container/container/container.ts
- src/elements/container/container/container.visual.spec.ts
- src/elements/container/container/readme.md
- src/elements/container/sticky-bar/readme.md
- src/elements/container/sticky-bar/sticky-bar.scss
- src/elements/container/sticky-bar/sticky-bar.stories.ts
- src/elements/container/sticky-bar/sticky-bar.ts
- src/elements/container/sticky-bar/sticky-bar.visual.spec.ts
This PR Closes #3171 
- add new color `midnight` and `charcoal` variants for the sbb-container and the sbb-sticky-bar
- add a note about consumers setting `negative` if needed when a dark background is used
> feat(sbb-container, sbb-sticky-bar): add new color variants

- .storybook/preview.ts
- src/elements/overlay/overlay-base-element.ts
> fix: display non bubbling events in storybook actions

- src/elements/dialog/dialog-title/__snapshots__/dialog-title.snapshot.spec.snap.js
- src/elements/title/__snapshots__/title.snapshot.spec.snap.js
- src/elements/title/title-base.ts
According to https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role#description
> Writing `<h2 role="presentation">Democracy Dies in Darkness</h2>` removes the heading semantics of the [h2](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) element, making it the equivalent of `<div>Democracy Dies in Darkness</div>`. The heading role semantics are removed, but the content itself is still available.
> refactor(sbb-title, sbb-dialog-title): remove obsolete h1-h6 tags

- src/elements/radio-button/radio-button-group/radio-button-group.spec.ts
- src/elements/radio-button/radio-button-group/radio-button-group.ts
Currently if there is a `change` from a radio button inside a radio button group that is nested in another radio button group, the outer radio button group also emits a `didChange` event. This fix checks whether the target of an event is actually directly contained in a group.
> fix(sbb-radio-button-group): prevent didChange emit from nested group

- src/elements/core/dom/scroll.ts
With previously introduced changes to scroll block, in certain situation the content is slightly moving. This happens when there is a scroll bar visible and some content is aligned next to the scrollbar.
Setting the height to 100dvh ensures that the body is always taking the full available height which is necessary e.g. for the sidebar. 
Setting `position: relative` reverts the previous change where this was removed. This change mainly avoids moving content.
> fix: avoid moving content when blocking scrolling

- src/elements/breadcrumb/breadcrumb-group/__snapshots__/breadcrumb-group.snapshot.spec.snap.js
- src/elements/breadcrumb/breadcrumb-group/breadcrumb-group.ts
- src/elements/breadcrumb/breadcrumb-group/readme.md
- src/elements/breadcrumb/breadcrumb/readme.md
- src/elements/button/accent-button-link/readme.md
- src/elements/button/button-link/readme.md
- src/elements/button/secondary-button-link/readme.md
- src/elements/button/transparent-button-link/readme.md
- src/elements/card/card-link/readme.md
- src/elements/core/base-elements/link-base-element.spec.ts
- src/elements/core/base-elements/link-base-element.ts
- src/elements/header/header-link/readme.md
- src/elements/header/header/header.stories.ts
- src/elements/header/header/readme.md
- src/elements/link/block-link/readme.md
- src/elements/link/link/readme.md
- src/elements/menu/menu-link/readme.md
- src/elements/navigation/navigation-link/readme.md
- src/elements/navigation/navigation-section/readme.md
- src/elements/navigation/navigation/readme.md
- src/elements/teaser-hero/readme.md
- src/elements/teaser-product/teaser-product/readme.md
- src/elements/teaser/readme.md
With the previous implementation, the `aria-current` was set on the host (e.g. in breadcrumb or navigation). However, this was not forwarded to the inner anchor tag which resulted in partially broken screen reader support. This PR introduces the `accessibility-current` property on link elements which forwards the value to the inner anchor element as `aria-current`.
> fix: provide `accessibility-current` property for link elements

- package.json
- src/elements/core/testing/private/a11y-tree-snapshot.ts
- web-test-runner.config.ts
- yarn.lock
We kept the puppeteer configuration just for the possibility of debugging tests.
Since we found a way to do it with Playwright, it does not add any value anymore. 
Plus, tests do not run consistently on it (I was probably the only one using it)
> chore: remove puppeteer dependency

- docs/GETTING_STARTED.md
It is - in my opinion - not obvious that I need to make a JavaScript import in the TypeScript file of my component to use a lyne-component in its template.
(also, that was not necessary in the "older" lyne-components dependency)
> docs: added warning about necessary import in type-script file

- src/elements-experimental/journey-summary/journey-summary.stories.ts
- src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.stories.ts
- src/elements/autocomplete/autocomplete.stories.ts
- src/elements/card/card/card.stories.ts
- src/elements/checkbox/checkbox-group/checkbox-group.stories.ts
- src/elements/chip-label/chip-label.stories.ts
- src/elements/clock/clock.stories.ts
- src/elements/container/sticky-bar/sticky-bar.stories.ts
- src/elements/datepicker/datepicker-next-day/datepicker-next-day.stories.ts
- src/elements/datepicker/datepicker-previous-day/datepicker-previous-day.stories.ts
- src/elements/datepicker/datepicker-toggle/datepicker-toggle.stories.ts
- src/elements/datepicker/datepicker/datepicker.stories.ts
- src/elements/dialog/dialog-actions/dialog-actions.stories.ts
- src/elements/dialog/dialog/dialog.stories.ts
- src/elements/divider/divider.stories.ts
- src/elements/flip-card/flip-card-summary/flip-card-summary.stories.ts
- src/elements/flip-card/flip-card/flip-card.stories.ts
- src/elements/footer/footer.stories.ts
- src/elements/form-error/form-error.stories.ts
- src/elements/form-field/form-field/form-field.stories.ts
- src/elements/logo/logo.stories.ts
- src/elements/map-container/map-container.stories.ts
- src/elements/menu/menu-button/menu-button.stories.ts
- src/elements/menu/menu-link/menu-link.stories.ts
- src/elements/message/message.stories.ts
- src/elements/option/optgroup/optgroup.stories.ts
- src/elements/select/select.stories.ts
Some minor fixes on stories
- Removal of useless `styleMap` in points where there's no need for interpolation
- Fixed a bug in optgroup.stories.ts: options need a unique value, otherwise the keyboard navigation will mark two options as selected
> chore: minor fixes on stories

- tools/vite/typescript-transform.ts
Currently istanbul (code coverage) incorrectly resolves the source paths, as they are wrongly generated by the TypeScript compilation.
> build: fix code coverage generation

- src/elements/core/mixins/form-associated-input-mixin.ts
Currently we do not use `contenteditable="plaintext-only"` on Firefox, as it was not supported. Now that support has landed, we are switching to feature detection.
> refactor(sbb-date-input): feature detect plaintext-only support

- src/elements/core/datetime/native-date-adapter.spec.ts
- src/elements/core/datetime/native-date-adapter.ts
Currently we use `createDate` inside `parse`, which throws on invalid date. However, `parse` should never throw, just return `null` for an invalid date, which this PR addresses.
> fix: avoid throwing on parsing invalid date

- web-test-runner.config.ts
This PR adapts the web test runner config to only use the inlined font-face for testing.
> test: use inlined font-face for testing

- eslint.config.js
- scripts/calculate-stats.ts
- scripts/migrate-ssr-e2e.ts
- scripts/migrate-ssr.ts
- scripts/migrate-toggle-data-entry.ts
- src/react/core/create-component.ts
- src/visual-regression-app/package.json
- src/visual-regression-app/src/components/test-case/image-diff/fullscreen-diff/fullscreen-diff.ts
- src/visual-regression-app/src/components/test-case/image-diff/image-diff.ts
- src/visual-regression-app/src/components/test-case/test-case-filter/test-case-filter.ts
- src/visual-regression-app/src/components/test-case/test-case.ts
- tools/eslint/index.ts
- tools/eslint/relative-imports-rule.ts
- tools/web-test-runner/configure-container-playwright-browser.ts
This PR adds an eslint rule to only allow relative imports inside a package. It also implements a fixer to automatically fix failing cases.
> build: add lint rule for only using relative imports inside package

- src/elements/core/styles/mixins/table.scss
- src/elements/core/styles/table.scss
- src/elements/table/table-wrapper/table-wrapper.scss
- src/elements/table/table-wrapper/table-wrapper.stories.ts
- src/storybook/styles/table/readme.md
- src/storybook/styles/table/table.stories.ts
- src/storybook/styles/table/table.visual.spec.ts
Propaedeutic to the angular table example
Implementation of https://www.figma.com/design/mWknI2rC5DJmOgRO61WKai/Lyne-Components?node-id=11340-100695&m=dev
> style(sbb-table): add support to header filters

- src/elements/alert/alert/alert.ts
- src/elements/clock/clock.ts
- src/elements/core/mixins/form-associated-input-mixin.ts
- src/elements/image/image.ts
- src/elements/notification/notification.ts
- src/elements/radio-button/radio-button-group/radio-button-group.ts
- src/elements/stepper/stepper/stepper.ts
- src/elements/toggle/toggle/toggle.ts
BREAKING CHANGE: removed async modifier of all firstUpdated() overrides.
> refactor: remove async overrides to avoid changing signature

- src/elements/select/select.component.ts
Closes #3597 
Useful info:
In Angular, bound properties `[value]="..."` are interpreted after the connectedCallback is executed. 
In this case, I moved the init logic that was in the connectedCallback, in the willUpdate
> fix(sbb-select): strengthen value initialization

- src/elements/toggle/toggle-option/toggle-option.component.ts
- src/elements/toggle/toggle-option/toggle-option.scss
- src/elements/toggle/toggle/__snapshots__/toggle.snapshot.spec.snap.js
- src/elements/toggle/toggle/toggle.component.ts
- src/elements/toggle/toggle/toggle.scss
With the previous solution, on sbb.ch it causes problems when resizing the window. Furthermore, with the new solution, the correct pill can be shown earlier, preventing a rendering without the pill and therefore provides a smoother experience.
> fix(sbb-toggle): fix animation glitches

- src/elements/datepicker/datepicker/readme.md
The docs on the `sbb-datepicker` is broken
> docs: fix broken docs

- src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.component.ts
- src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.spec.ts
- src/elements/autocomplete-grid/autocomplete-grid-option/autocomplete-grid-option.stories.ts
- src/elements/autocomplete-grid/autocomplete-grid-option/readme.md
- src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.component.ts
- src/elements/autocomplete/autocomplete-base-element.ts
- src/elements/autocomplete/autocomplete.component.ts
- src/elements/option/option/option-base-element.ts
- src/elements/option/option/option.component.ts
- src/elements/select/select.component.ts
BREAKING CHANGE: Removed the following event and method
- removed autocompleteOptionSelectionChange event
- removed setSelectedViaUserInteraction method
> refactor: remove autocompleteOptionSelectionChange event

- src/elements/toast/__snapshots__/toast.snapshot.spec.snap.js
- src/elements/toast/toast.component.ts
- src/elements/toast/toast.snapshot.spec.ts
- src/elements/toast/toast.spec.ts
This PR Closes #3683
I had to move the `aria-live` in the light DOM (on the host) to be correctly interpreted by JAWS and NVDA
> fix(sbb-toast): fix a11y on windows browsers

- src/elements/select/select.component.ts
- src/elements/slider/slider.component.ts
> fix(sbb-select, sbb-slider): display readonly state correctly if set by property

- src/elements/skiplink-list/skiplink-list.scss
With our previous fix, we unintentionally caused the skiplink list to block the content behind it. This fix basically resets that behavior and prevents the skiplink list from taking up space.
> fix(sbb-skiplink-list): avoid invisible content block

- src/elements/overlay/overlay.component.ts
- src/elements/overlay/overlay.stories.ts
- src/elements/overlay/overlay.visual.spec.ts
- src/elements/overlay/readme.md
BREAKING CHANGE: removed back button from `sbb-overlay` as it was never intended to be used. Therefore properties `backButton` and `accessibilityBackLabel` were removed.
> refactor(sbb-overlay): remove back button

- src/elements/core/interfaces.ts
- src/elements/core/interfaces/validation-change.ts
- tools/vite/generate-react-wrappers.ts
This PR removes the obsolete `SbbValidationChangeEvent`. The functionality is now handled by native from validation.
> refactor: remove SbbValidationChangeEvent interface

- src/elements/datepicker/datepicker/datepicker.component.ts
Currently the `<sbb-calendar>` is rendered synchronously inside the `<sbb-datepicker>`. As the calendar is only needed once the datepicker needs to be opened, we can safely delay the rendering of the calendar.
Closes sbb-design-systems/lyne-angular#138
> perf(sbb-datepicker): delay rendering of calendar

- src/elements/form-field/form-field/form-field.component.ts
- src/elements/form-field/form-field/form-field.spec.ts
- src/elements/form-field/form-field/readme.md
This PR introduces the possibility of defining custom form controls for `<sbb-form-field>`.
The basic functionality is based on implementing the `SbbFormFieldElementControl` and dispatching the `SbbFormFieldControlEvent` on the related `<sbb-form-field>` instance.
This is the basis for supporting sbb-design-systems/lyne-angular#55
> feat(sbb-form-field): add support for custom controls

- src/elements/expansion-panel/expansion-panel-header/expansion-panel-header.scss
This PR allows overriding the position of the expansion arrow, by defining the `justify-content` property.
Closes #3912
> feat(sbb-expansion-panel-header): add CSS variable for justify-content

- src/elements/core/mixins/form-associated-mixin.ts
- src/elements/date-input/date-input.spec.ts
- src/elements/time-input/time-input.spec.ts
Previously, setting a custom form element into disabled state and re-enable it, failed. This fix changes the check for disabled ancestors by explicitly looking for them, instead of handling only the disabled value.
Closes [#lyne-angular/161](https://github.com/sbb-design-systems/lyne-angular/issues/161)
> fix: fix disabled state handling

- src/elements/tabs/tab-group/__snapshots__/tab-group.snapshot.spec.snap.js
- src/elements/tabs/tab-group/readme.md
- src/elements/tabs/tab-group/tab-group.component.ts
- src/elements/tabs/tab-group/tab-group.scss
- src/elements/tabs/tab-group/tab-group.spec.ts
- src/elements/tabs/tab-group/tab-group.stories.ts
- src/elements/tabs/tab-label/tab-label.component.ts
- src/elements/tabs/tab-label/tab-label.scss
- src/elements/tabs/tab/__snapshots__/tab.snapshot.spec.snap.js
- src/elements/tabs/tab/readme.md
- src/elements/tabs/tab/tab.component.ts
- src/elements/tabs/tab/tab.scss
- src/elements/tabs/tab/tab.stories.ts
In previous implementation, the `tab` reference in the `tabLabel` was observed by the `_tabContentResizeObserver` when the tab was activated (unobserving the previous selected one).
This logic has been lost moving the select/activate method from the tab-group to the tab-label; a possible solution is the logic added in the current PR.
Other options:
- move the observer in the tab-label and restore the .observe/.unobserve methods in the `activate` method (drawback: the height must be changed on the tab wrapper in the group, so querying it from the tab-label requires something like: `this.group?.shadowRoot.querySelector('.sbb-tab-group-content)?.style.height = ...`, which I don't really like);
- listen to the `active` event emitted by the tab to connect the observer
- listen to the …
> fix(sbb-tab): fix height observer and animation
