sbb-design-systems/lyne-components

- .travis.yml
> fix: test closing pr and issue

- .travis.yml
> fix: fake commit to test projects

- .github/workflows/assign-issues-and-pr-to-project.yml
- .travis.yml
> Workflow test

- docs/VISION.md
> fix: change incorrect link to the glossary#single-source-of-truth

- src/components/lyne-cta-button/lyne-cta-button.scss
> fix: add green border

- .travis.yml
- src/components/lyne-heading/lyne-heading.scss
> fix: fake commit to trigger build

- src/components/lyne-heading/lyne-heading.scss
> fix: set border color to yellow

- src/components/lyne-cta-button/lyne-cta-button.scss
> fix: remove border color

- src/components/lyne-link/lyne-link.d.ts
- src/components/lyne-link/lyne-link.e2e.ts
- src/components/lyne-link/lyne-link.scss
- src/components/lyne-link/lyne-link.spec.ts
- src/components/lyne-link/lyne-link.stories.js
- src/components/lyne-link/lyne-link.tsx
- src/components/lyne-link/readme.md
> feat: temporary add lyne-link

- .travis.yml
> fix: add correct version number when building storybook

- src/components.d.ts
- src/components/lyne-link/lyne-link.d.ts
- src/components/lyne-link/lyne-link.e2e.ts
- src/components/lyne-link/lyne-link.scss
- src/components/lyne-link/lyne-link.spec.ts
- src/components/lyne-link/lyne-link.stories.js
- src/components/lyne-link/lyne-link.tsx
- src/components/lyne-link/readme.md
> feat: add link component

- src/components/lyne-cta-button/lyne-cta-button.scss
> fix: remove green border

- TODOS.md
> fix: (b) fake commit to test merges

- TODOS.md
> fix: (a) fake commit to test merges

- .travis.yml
> fix: remove lyne-documentation trigger for branches that are not master

- .travis.yml
- src/components/lyne-heading/lyne-heading.tsx
> chore: add test method and thus change code coverage

- package-lock.json
- package.json
> fix: update design tokens

- README.md
> docs: link current tasks with repo entry docs page

- src/components/lyne-panel/lyne-panel.custom.d.ts
- src/components/lyne-panel/readme.md
> fix: remove non existent html element

- src/components/lyne-card-badge/lyne-card-badge.stories.js
- src/components/lyne-card-product/lyne-card-product.stories.js
- src/components/lyne-card-product/styles/lyne-card-product.component.scss
- src/components/lyne-journey-header/lyne-journey-header.stories.js
This PR Closes #941 
- Fixes documentation platform issues
Fixes #941 
> fix card issues on documentation platform

- src/components/lyne-card-badge/lyne-card-badge.stories.js
- src/components/lyne-card-product/lyne-card-product.stories.js
- src/components/lyne-journey-header/lyne-journey-header.stories.js
This PR Closes #943 
- Extends documentation container styles
> feat: introducing documentation styles for all

- .github/ISSUE_TEMPLATE/story.yml
> docs: add story isse template

- src/components/lyne-image/lyne-image.tsx
No issue created for this issue, just this PR.
- how the image aria-hidden gets rendered
> fix: aria-hidden dash issue to render lyne-image's figure attributes correctly

- src/components/lyne-image/lyne-image.tsx
To fully benefit from the opportunities that imgix (or just another image cdn service) offers, it will be usefull to put additional properties to Lyne Image component.
A possibility was created, that a developer is able to specify additional attributes by adding these parameters to image URL (image-src).
Examples
- add property to flip axis horizontal (flip): 
https://cdn.img.sbb.ch/content/dam/internet/lyne/Billetkontrolle.jpg?flip=h
- override property for quality (q) that was automatically added by Lyne Image component:  https://cdn.img.sbb.ch/content/dam/internet/lyne/Billetkontrolle.jpg?q=15
Please check the type of change your PR …
> feat: add support for additional imgix Rendering API parameters

- docs/STATES.md
Add documentation for component states
> docs: add documentation for component states

- .storybook/preview.js
- src/components/lyne-footer/lyne-footer.stories.js
- src/components/lyne-teaser-hero/lyne-teaser-hero.stories.js
Remove page sections with components
> refactor(page sections): remove page sections

- .github/workflows/continuous-integration.yml
Temporarily ignore errors from chromatic
> ci: ignore chromatic failure

- .github/workflows/release.yml
- Remove double quotes, trying to solve: https://github.com/lyne-design-system/lyne-components/runs/7043810468?check_suite_focus=true
> fix: remove quotes when set STORYBOOK_COMPONENTS_VERSION variable

- .github/ISSUE_TEMPLATE/00-accessibility-issue.md
- .github/ISSUE_TEMPLATE/00-documentation-issue.md
- .github/ISSUE_TEMPLATE/00-performance-issue.md
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request-or-enhancement.yml
- .github/ISSUE_TEMPLATE/question.md
- .github/pull_request_template.md
> docs: fix links in github templates

- .github/workflows/continuous-integration.yml
- .github/workflows/release.yml
- .storybook/preview.js
This PR also adds functionality to create comments on pull requests with successful chromatic storybook deployments.
> build: fix chromatic deployment

- src/components.d.ts
- src/components/sbb-icon/readme.md
- src/components/sbb-icon/sbb-icon.scss
- src/components/sbb-icon/sbb-icon.spec.ts
- src/components/sbb-icon/sbb-icon.tsx
- add width and height CSS vars in order to resize the icon
- fix Safari behaviour on initial rendering
- refactor ARIA attributes properties
> feat(sbb-icon): add width and height CSS variables and refactor

- src/components/sbb-toggle-check/sbb-toggle-check.scss
- add `user-select: none` to prevent the toggle from freezing on double-click.
- remove mobile tap highlight color.
> fix(sbb-toggle-check): prevent the toggle from freezing on double-click

- src/components.d.ts
- src/components/sbb-toggle-check/readme.md
- src/components/sbb-toggle-check/sbb-toggle-check.scss
- src/components/sbb-toggle-check/sbb-toggle-check.spec.ts
- src/components/sbb-toggle-check/sbb-toggle-check.stories.js
- src/components/sbb-toggle-check/sbb-toggle-check.tsx
- src/global/mixins.scss
- Removes space around component
- Adds windows high contrast support
- Simplifies code
> fix(sbb-toggle-check): fix various issues

- src/global/interfaces/link-button-properties.ts
- a new interface has been added to give common attributes in all the cases where a component can render an anchor or a button based on the href attribute value.
> refactor: add common interface for link/button cases

- src/components/sbb-button/sbb-button.stories.js
- src/components/sbb-button/sbb-button.tsx
- src/components/sbb-icon/readme.md
- the eventId is not emitted on sbb-button due the wrong context in anonymous function; this behavior has been fixed.
> fix(sbb-button): button doesn't emit eventId

- src/components/sbb-link/sbb-link.scss
- src/components/sbb-link/sbb-link.spec.ts
- src/components/sbb-link/sbb-link.stories.js
- src/components/sbb-link/sbb-link.tsx
- handle icon slot and icon placement correctly
- remove flip icon class
> fix(sbb-link): handle icon slot and icon placement correctly

- src/components/sbb-tab-group/sbb-tab-group.e2e.ts
- src/components/sbb-tab-group/sbb-tab-group.tsx
- improve tab buttons selection and mutation observer
> refactor(sbb-tab-group): improve tabs selection

- .prettierignore
- convenience/generate-component/boilerplate/readme.md
- convenience/generate-component/index.js
- the 'styles' folder generation ha s been removed, since the folder is empty;
- the readme.md needs `__name__ ` as placeholder, but prettier changes it to `**name**` during yarn format, so the file has been added to the .prettierignore file and the placeholder has been restored.
> chore: improvement for generate script

- src/components/sbb-link/sbb-link.scss
- src/components/sbb-link/sbb-link.spec.ts
- src/components/sbb-link/sbb-link.stories.js
- src/components/sbb-link/sbb-link.tsx
- src/global/interfaces/link-button-properties.spec.ts
- src/global/interfaces/link-button-properties.ts
> fix(sbb-link): fix accessibility of external links

- react-library/tsconfig.json
This PR should fix the output format of our react output, by using the correct jsx factory for react.
> fix: use correct jsx factory for react output target

- src/global/core/shared/variables.scss
- src/global/mixins/mixins_typo.scss
- src/global/theme/sbb-ch/mode--compact/variables.scss
Closes [Add new typo size "L" to design tokens #437](https://github.com/lyne-design-system/lyne-design-tokens/issues/437)
> feat: add new text size l

- src/components/sbb-card/sbb-card.scss
> fix: animation duration

- src/components/sbb-link/sbb-link.scss
- src/components/sbb-link/sbb-link.spec.ts
- src/components/sbb-link/sbb-link.stories.js
- src/components/sbb-link/sbb-link.tsx
> fix(sbb-link): expand clickable area in block variant

- package.json
- src/global/helpers/timezone-helper.spec.ts
- src/global/helpers/timezone-helper.ts
- yarn.lock
- Add a helper function to ignore the offset from an other timezone
> feat: add removeTimezoneFromDate as a helper function

- src/components/sbb-button/sbb-button.tsx
- src/components/sbb-link/sbb-link.tsx
Provide `sbb-button` and `sbb-link` with `type="submit"` with the ability to submit the form in which they are embedded.
> feat: add possibility to submit forms with sbb-button/sbb-link

- src/components/sbb-action-group/sbb-action-group.scss
- add a gap variable to handle both vertical case (2x) and horizontal case (4x)
> style(sbb-action-group): fix gap for vertical orientation

- src/components/sbb-icon/sbb-icon.spec.ts
- fix a TS error in tests that pops out during yarn start
> fix: typescript error

- src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.helper.spec.ts
- src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.helper.ts
- src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.stories.js
- src/components/sbb-pearl-chain/sbb-pearl-chain.sample-data.js
the sbb-pearl-chain and sbb-pearl-chain-time has two datetime parameters, named 'arrival-time' and 'departure-time'; now the values of those are static ones (e.g. `2022-10-28T02:48:00+02:00`).
This caused diffs to be reported in Chromatic when the dates passed; to solve this problem, relative dates are introduced (e.g. `new Date().setHours(4, 48, 0, 0)`). Also, an util function has been added to correctly display numbers in Storybook's controls.
> fix(sbb-pearl-chain, sbb-pearl-chain-time): relative datetime in stories

- src/components/sbb-menu/sbb-menu.scss
- src/components/sbb-menu/sbb-menu.tsx
- src/global/helpers/focus.ts
- src/global/helpers/position.spec.ts
- src/global/helpers/position.ts
Improved handling of window-related events, improved positioning function, and extracted logic for focus trapping.
> refactor(sbb-menu): improve menu events and positioning

- convenience/generate-component/boilerplate/component.e2e.ts
- add import in boilerplate code for 'generate' script
> build: fix component generation typings

- src/components.d.ts
- src/components/sbb-logo/readme.md
- src/components/sbb-logo/sbb-logo.custom.d.ts
- src/components/sbb-logo/sbb-logo.scss
- src/components/sbb-logo/sbb-logo.stories.js
- src/components/sbb-logo/sbb-logo.tsx
- src/components/sbb-signet/readme.md
- src/components/sbb-signet/sbb-signet.custom.d.ts
- src/components/sbb-signet/sbb-signet.scss
- src/components/sbb-signet/sbb-signet.stories.js
- src/components/sbb-signet/sbb-signet.tsx
- sbb-logo no longer has different color variants
- sbb-signet no longer has white-on-black variant
> refactor(sbb-signet): adapt to coding standards

- src/components/sbb-timetable-row/sbb-timetable-row.tsx
- src/global/i18n.ts
> fix(sbb-timetable-row): handle occupancy error

- src/components/sbb-radio-button/sbb-radio-button.scss
- remove the small red dot that appeared on unselected radios
> fix(sbb-radio-button): remove red dot on low resolution screens

- src/components/sbb-button/readme.md
- src/components/sbb-checkbox-group/readme.md
- src/components/sbb-checkbox/readme.md
- src/components/sbb-header-action/readme.md
- src/components/sbb-header/readme.md
- src/components/sbb-journey-summary/readme.md
- src/components/sbb-pearl-chain-vertical-item/readme.md
- src/components/sbb-pearl-chain-vertical/readme.md
- src/components/sbb-slider/readme.md
- src/components/sbb-teaser-hero/readme.md
- src/components/sbb-timetable-row/readme.md
- fix in the components doc view: without a line break the snippets appear broken
> docs: fix snippets in readme

- src/components/sbb-toggle-check/sbb-toggle-check.scss
- src/components/sbb-toggle-check/sbb-toggle-check.spec.ts
- src/components/sbb-toggle-check/sbb-toggle-check.stories.js
- src/components/sbb-toggle-check/sbb-toggle-check.tsx
sbb-toggle-check missed vertical alignment for the toggle element
- vertical alignment for toggle element
- added variant with long label 
> fix(sbb-toggle-check): fix toggle vertical alignment

- convenience/generate-component/boilerplate/component.tsx
- src/components/sbb-accordion-item/sbb-accordion-item.tsx
- src/components/sbb-accordion/sbb-accordion.tsx
- src/components/sbb-alert/sbb-alert.tsx
- src/components/sbb-autocomplete/sbb-autocomplete.tsx
- src/components/sbb-button/sbb-button.tsx
- src/components/sbb-card-badge/sbb-card-badge.tsx
- src/components/sbb-card-product/sbb-card-product.tsx
- src/components/sbb-card/sbb-card.tsx
- src/components/sbb-checkbox/sbb-checkbox.tsx
- src/components/sbb-clock/sbb-clock.tsx
- src/components/sbb-dialog/sbb-dialog.tsx
- src/components/sbb-grid/sbb-grid.tsx
- src/components/sbb-header-action/sbb-header-action.tsx
- src/components/sbb-icon/sbb-icon.tsx
- src/components/sbb-image/sbb-image.tsx
- src/components/sbb-journey-summary/sbb-journey-summary.tsx
- src/components/sbb-link-list/sbb-link-list.tsx
- src/components/sbb-link/sbb-link.tsx
- src/components/sbb-menu-action/sbb-menu-action.tsx
- src/components/sbb-radio-button-group/sbb-radio-button-group.tsx
- src/components/sbb-radio-button/sbb-radio-button.tsx
- src/components/sbb-section/sbb-section.tsx
- src/components/sbb-tab-group/sbb-tab-group.tsx
- src/components/sbb-teaser-hero/sbb-teaser-hero.tsx
- src/components/sbb-teaser/sbb-teaser.tsx
- src/components/sbb-timetable-button/sbb-timetable-button.tsx
- a component that uses StencilJS hooks (like componentDidLoad(..), connectedCallback(..) etc) should implement ComponentInterface, otherwise the (working) method will be marked as unused from the IntelliJ compiler.
> chore: add ComponentInterface in components

- src/components/sbb-checkbox-group/sbb-checkbox-group.tsx
- src/components/sbb-checkbox/sbb-checkbox.tsx
- src/components/sbb-radio-button-group/sbb-radio-button-group.tsx
- src/components/sbb-tab-group/sbb-tab-group.tsx
- src/global/helpers/arrow-navigation.spec.ts
- src/global/helpers/arrow-navigation.ts
- sbb-checkbox-group has arrow navigation logic;
- so now there are three group components (five with the new sbb-tag-group and sbb-toggle) that share almost the same logic about arrow navigation; it has been extracted and refactored.
> fix: arrow navigation refactoring

- src/components/sbb-form-field/sbb-form-field.scss
- src/components/sbb-form-field/sbb-form-field.stories.js
The border radius should be 8px (4x) both variants (M and L)
- The border radius is now the same for both variants (M and L) 
> fix(sbb-form-field): fix border radius for size L

- src/components/sbb-timetable-row/sbb-timetable-row.scss
> fix(sbb-timetable-row): fix px-to-rem usage

- src/components/sbb-pearl-chain/sbb-pearl-chain.sample-data.js
- src/components/sbb-pearl-chain/sbb-pearl-chain.scss
- src/components/sbb-pearl-chain/sbb-pearl-chain.spec.ts
- src/components/sbb-pearl-chain/sbb-pearl-chain.stories.js
- src/components/sbb-pearl-chain/sbb-pearl-chain.tsx
- src/components/sbb-timetable-row/sbb-timetable-row.sample-data.js
- src/components/sbb-timetable-row/sbb-timetable-row.stories.js
- src/global/interfaces/pearl-chain-properties.ts
> refactor(sbb-pearl-chain): add bullet to pearl-chain

- src/components/sbb-pearl-chain-vertical-item/sbb-pearl-chain-vertical-item.scss
- src/components/sbb-pearl-chain/sbb-pearl-chain.scss
- src/global/styles/mixins/pearl-chain-bullet.scss
> fix(sbb-pearl-chain): use min-width to prevent squeezing

- src/components.d.ts
- src/components/sbb-train-formation/sbb-train-formation.scss
- src/components/sbb-train-formation/sbb-train-formation.stories.js
- src/components/sbb-train/readme.md
- src/components/sbb-train/sbb-train.spec.ts
- src/components/sbb-train/sbb-train.stories.js
- src/components/sbb-train/sbb-train.tsx
- src/components/sbb-wagon/sbb-wagon.stories.js
- src/components/sbb-wagon/sbb-wagon.tsx
- [x ] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x ] I have searched the [pull request tracker](https://github.com/lyne-design-system/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.
-
> fix(sbb-train-formation): minor fixes

- src/components.d.ts
- src/components/sbb-timetable-row/readme.md
- src/components/sbb-timetable-row/sbb-timetable-row.custom.d.ts
- src/components/sbb-timetable-row/sbb-timetable-row.helper.spec.ts
- src/components/sbb-timetable-row/sbb-timetable-row.helper.tsx
- src/components/sbb-timetable-row/sbb-timetable-row.sample-data.js
- src/components/sbb-timetable-row/sbb-timetable-row.stories.js
- src/components/sbb-timetable-row/sbb-timetable-row.tsx
> fix(sbb-timetable-row): remove unnecessary notices

- src/global/helpers/timezone-helper.spec.ts
- src/global/helpers/timezone-helper.ts
> fix: enhance timezone helper

- src/components/sbb-timetable-row/sbb-timetable-row.helper.tsx
> fix(sbb-timetable-row): enhance icon mapping

- src/components/sbb-tag/sbb-tag.scss
This PR fixes an issue reported by Aleksandar from team Lynx, related to both storybook and his aem environment:
Tag elements are not correctly displayed
- fixed tag element display (background, border, animations)
> fix(sbb-tag): fix styles

- src/components/sbb-card/sbb-card.scss
This PR Closes #1529
- change style for active state
> fix(sbb-card): fix active style for badge

- src/components/sbb-navigation/sbb-navigation.scss
- src/components/sbb-navigation/sbb-navigation.tsx
- src/global/helpers/scroll.ts
This PR Closes #1523 
- implement `scroll.ts` helper to handle the page scrolling behaviour when the navigation is open
> feat(sbb-navigation): handle scrolling behaviour on navigation open

- src/components/sbb-card-badge/sbb-card-badge.scss
- src/components/sbb-timetable-row/sbb-timetable-row.helper.tsx
- src/components/sbb-timetable-row/sbb-timetable-row.scss
- src/components/sbb-timetable-row/sbb-timetable-row.tsx
> fix(sbb-timetable-row): fix notices issue

- src/components/sbb-teaser/sbb-teaser.scss
> fix(sbb-teaser): fix hover state

- src/components/sbb-dialog/sbb-dialog.scss
- src/components/sbb-dialog/sbb-dialog.tsx
- src/storybook/pages/home/home--logged-in.stories.js
- stabilize dialog wrapper position (Chrome)
- handle scrolling with `ScrollHandler` class
- fix close button position on full-screen and without back button
> fix(sbb-dialog): stabilize dialog content position

- src/components/sbb-tooltip/sbb-tooltip.scss
- src/components/sbb-tooltip/sbb-tooltip.tsx
- src/global/helpers/position.spec.ts
- src/global/helpers/position.ts
- optimized positioning on window scrolling and resizing
- added `hideCloseButton` prop (useful, , e.g., for the `sbb-datepicker` placed inside the tooltip)
> refactor(sbb-tooltip): optimize positioning and add `hideCloseButton` prop

- src/components/sbb-accordion-item/sbb-accordion-item.stories.js
- src/components/sbb-accordion/sbb-accordion.stories.js
- src/components/sbb-button/sbb-button.stories.js
- src/components/sbb-card-badge/sbb-card-badge.stories.js
- src/components/sbb-card-product/sbb-card-product.stories.js
- src/components/sbb-card/sbb-card.stories.js
- src/components/sbb-divider/sbb-divider.stories.js
- src/components/sbb-title/sbb-title.stories.js
- tokens have been removed in stories and replaced with CSS variables
> refactor: prefer CSS variables to tokens

- src/components/sbb-dialog/sbb-dialog.scss
- handle content wrapper overflow behaviour on mobile
> fix(sbb-dialog): avoid unwanted scroll on mobile

- src/components/sbb-footer/sbb-footer.scss
This PR Closes #1535
- align clock to the right on wide and ultra breakpoints inside the footer
> fix(sbb-footer): align clock to right on wide and ultra breakpoints

- src/components/sbb-dialog/sbb-dialog.e2e.ts
- src/components/sbb-menu/sbb-menu.e2e.ts
- src/components/sbb-navigation/sbb-navigation.e2e.ts
- src/components/sbb-tooltip-trigger/sbb-tooltip-trigger.e2e.ts
- src/components/sbb-tooltip-trigger/sbb-tooltip-trigger.scss
- src/components/sbb-tooltip/sbb-tooltip.e2e.ts
This PR Closes #1563
- improved dialog tests
- improved menu tests
- improved navigation tests
- improved tooltip tests
- improved tooltip-trigger tests
- improved Esc keypress tests
> test: improve and stabilize overlay components tests

- src/components.d.ts
- src/components/sbb-journey-summary/readme.md
- src/components/sbb-journey-summary/sbb-journey-summary.custom.d.ts
- src/components/sbb-journey-summary/sbb-journey-summary.scss
- src/components/sbb-journey-summary/sbb-journey-summary.spec.ts
- src/components/sbb-journey-summary/sbb-journey-summary.stories.js
- src/components/sbb-journey-summary/sbb-journey-summary.tsx
> fix(sbb-journey-summary): minor fixes

- src/components.d.ts
- src/components/sbb-navigation-action/readme.md
- src/components/sbb-navigation-action/sbb-navigation-action.tsx
- src/components/sbb-navigation-marker/readme.md
- src/components/sbb-navigation-marker/sbb-navigation-marker.e2e.ts
- src/components/sbb-navigation-marker/sbb-navigation-marker.scss
- src/components/sbb-navigation-marker/sbb-navigation-marker.spec.ts
- src/components/sbb-navigation-marker/sbb-navigation-marker.tsx
- src/components/sbb-navigation-section/readme.md
- src/components/sbb-navigation-section/sbb-navigation-section.tsx
- src/components/sbb-navigation/readme.md
- src/components/sbb-navigation/sbb-navigation.tsx
- src/components/sbb-tab-group/readme.md
- src/components/sbb-tab-group/sbb-tab-group.tsx
- src/components/sbb-toggle-option/readme.md
- src/components/sbb-toggle-option/sbb-toggle-option.tsx
- src/storybook/pages/home/home.common.js
- handled `active` attribute change in the DOM on navigation actions
- removed styles and classes from host tag
> feat(sbb-navigation): handle `active` attr change on navigation actions

- src/components/sbb-timetable-row/sbb-timetable-row.helper.tsx
> fix(sbb-timetable): remove unwanted notices

- src/components/sbb-journey-summary/sbb-journey-summary.tsx
> fix(sbb-journey-summary): remove unnecessary commas

- react-library/src/components/stencil-generated/index.ts
- src/components.d.ts
- src/components/sbb-group/readme.md
- src/components/sbb-group/sbb-group.chromatic.stories.js
- src/components/sbb-group/sbb-group.custom.d.ts
- src/components/sbb-group/sbb-group.e2e.ts
- src/components/sbb-group/sbb-group.scss
- src/components/sbb-group/sbb-group.spec.ts
- src/components/sbb-group/sbb-group.stories.js
- src/components/sbb-group/sbb-group.tsx
- src/global/styles/_index.scss
- src/global/styles/mixins/group.scss
> feat(sbb-group): initial implementation

- src/components.d.ts
> fix: integrity

- src/components/sbb-button/sbb-button.scss
- src/components/sbb-header-action/sbb-header-action.scss
- src/components/sbb-header-action/sbb-header-action.spec.ts
- src/components/sbb-header-action/sbb-header-action.tsx
- src/storybook/pages/home/home--logged-in.stories.js
- src/storybook/pages/home/home.stories.js
This PR Closes the bug reported by Florian, about missing animation on hover of header action elements
https://github.com/lyne-design-system/lyne-components/issues/1569
- added translation to text and icon, when header action is hovered
> fix(sbb-header): header action animation on hover

- src/components/sbb-checkbox/sbb-checkbox.scss
- src/components/sbb-radio-button/sbb-radio-button.scss
> fix(sbb-checkbox, sbb-radio-button): fix windows high contrast styles

- src/components/sbb-journey-summary/sbb-journey-summary.spec.ts
- src/components/sbb-journey-summary/sbb-journey-summary.tsx
- src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.tsx
- src/components/sbb-pearl-chain/sbb-pearl-chain.sample-data.js
- src/components/sbb-pearl-chain/sbb-pearl-chain.tsx
- src/components/sbb-timetable-row/sbb-timetable-row.helper.spec.ts
- src/components/sbb-timetable-row/sbb-timetable-row.helper.tsx
- src/components/sbb-timetable-row/sbb-timetable-row.tsx
- src/global/helpers/date-helper.spec.ts
- src/global/helpers/date-helper.ts
- src/global/interfaces/pearl-chain-properties.ts
- src/global/styles/mixins/pearl-chain-bullet.scss
> fix(timetable): apply change requests

- src/components/sbb-image/sbb-image.scss
- src/components/sbb-image/sbb-image.stories.js
- src/components/sbb-image/sbb-image.tsx
- src/global/images.ts
> fix(sbb-button): support transparent picture with lqip

- src/components.d.ts
- src/components/sbb-tooltip-trigger/readme.md
- src/components/sbb-tooltip-trigger/sbb-tooltip-trigger.e2e.ts
- src/components/sbb-tooltip-trigger/sbb-tooltip-trigger.scss
- src/components/sbb-tooltip-trigger/sbb-tooltip-trigger.stories.js
- src/components/sbb-tooltip-trigger/sbb-tooltip-trigger.tsx
- Manage the disabled state for the `sbb-tooltip-trigger`
- Use aria-disabled when disabled
> feat(sbb-tooltip-trigger): add disable state

- src/components/sbb-toggle-check/sbb-toggle-check.e2e.ts
- src/components/sbb-toggle-check/sbb-toggle-check.scss
- src/components/sbb-toggle-check/sbb-toggle-check.spec.ts
- src/components/sbb-toggle-check/sbb-toggle-check.stories.js
- src/components/sbb-toggle-check/sbb-toggle-check.tsx
> fix(sbb-toggle-check): scroll into view when focused via tab key

- src/components.d.ts
- src/components/sbb-toggle-option/readme.md
- src/components/sbb-toggle-option/sbb-toggle-option.e2e.ts
- src/components/sbb-toggle-option/sbb-toggle-option.events.ts
- src/components/sbb-toggle-option/sbb-toggle-option.stories.js
- src/components/sbb-toggle-option/sbb-toggle-option.tsx
- src/components/sbb-toggle/sbb-toggle.e2e.ts
- src/components/sbb-toggle/sbb-toggle.tsx
> fix(sbb-toggle): send event on keyboard selection

- stencil.config.ts
- *.ts files (like the ones in src/global/helpers) are now counted in Jest's code coverage
> fix: add ts files in code coverage calculation

- src/components/sbb-dialog/sbb-dialog.tsx
Handle the resizing of the dialog content and apply the correct style to the dialog accordingly.
> fix(sbb-dialog): observe dialog content resizing

- src/components/sbb-tab-group/sbb-tab-group.scss
> fix(sbb-tab-group): remove unwanted space between tabs

- src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.spec.ts
- src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.tsx
- src/components/sbb-timetable-row/sbb-timetable-row.tsx
> fix(sbb-timetable-row): add spacings for sr-only text

- src/components/sbb-card/sbb-card.e2e.ts
- src/components/sbb-card/sbb-card.spec.ts
- src/components/sbb-card/sbb-card.tsx
> fix(sbb-card): change sbb-card-badge order

- src/components/sbb-pearl-chain-vertical-item/sbb-pearl-chain-vertical-item.scss
- src/components/sbb-pearl-chain/sbb-pearl-chain.scss
- src/components/sbb-timetable-row/sbb-timetable-row.scss
- src/global/styles/mixins/pearl-chain-bullet.scss
> fix(sbb-pearl-chain): use forced-colors on pearl-chain lines and dots

- src/components/sbb-pearl-chain-vertical-item/sbb-pearl-chain-vertical-item.scss
- src/components/sbb-pearl-chain-vertical-item/sbb-pearl-chain-vertical-item.spec.ts
- src/components/sbb-pearl-chain-vertical-item/sbb-pearl-chain-vertical-item.tsx
> fix(sbb-pearl-chain-vertical): improve spacing and a11y

- src/components/sbb-timetable-row/sbb-timetable-row.helper.spec.ts
- src/components/sbb-timetable-row/sbb-timetable-row.helper.tsx
- src/components/sbb-timetable-row/sbb-timetable-row.tsx
- src/global/i18n.ts
- src/global/interfaces/timetable-properties.ts
> fix(sbb-timetable-row): improve a11y text for himcus icons

- src/components/sbb-form-field/sbb-form-field.stories.js
- due changes to the sbb-form-field, the show-and-hide logic on the sbb-error was not working and needs to be fixed
> fix(sbb-form-field): wrong logic in error-space stories

- src/components/sbb-timetable-row/sbb-timetable-row.tsx
> fix(sbb-timetable-row): use sr-only span for icon label

- .stylelintrc.json
- convenience/generate-component/boilerplate/component.scss
- convenience/generate-component/boilerplate/component.stories.jsx
- convenience/generate-component/boilerplate/component.tsx
- react-library/src/components/stencil-generated/index.ts
- src/components.d.ts
- src/components/sbb-chip/readme.md
- src/components/sbb-chip/sbb-chip.custom.d.ts
- src/components/sbb-chip/sbb-chip.e2e.ts
- src/components/sbb-chip/sbb-chip.scss
- src/components/sbb-chip/sbb-chip.spec.ts
- src/components/sbb-chip/sbb-chip.stories.jsx
- src/components/sbb-chip/sbb-chip.tsx
- src/global/styles/_index.scss
- src/global/styles/mixins/chip.scss
> feat(sbb-chip): initial implementation

- src/components/sbb-button/sbb-button.scss
- src/components/sbb-checkbox/sbb-checkbox.scss
- src/components/sbb-form-field/sbb-form-field.scss
- src/components/sbb-form-field/sbb-form-field.stories.jsx
- src/components/sbb-radio-button/sbb-radio-button.scss
- src/components/sbb-tag/sbb-tag.scss
- src/components/sbb-time-input/sbb-time-input.scss
- src/components/sbb-toggle-check/sbb-toggle-check.scss
- src/components/sbb-toggle-option/sbb-toggle-option.scss
- src/global/styles/mixins/buttons.scss
- src/global/styles/mixins/typo.scss
- src/global/styles/typography.scss
The disabled state of the following components were updated:
- button
- checkbox
- radio button
- select
- tabs
- tag
- toggle
- toggle-check
- time-input
- text-input
- date-input
> fix: new disabled states

- src/components/sbb-button/readme.md
- src/components/sbb-button/sbb-button.scss
- src/components/sbb-button/sbb-button.spec.ts
- src/components/sbb-button/sbb-button.stories.jsx
- src/components/sbb-button/sbb-button.tsx
- src/components/sbb-datepicker-next-day/sbb-datepicker-next-day.scss
- src/components/sbb-datepicker-next-day/sbb-datepicker-next-day.tsx
- src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.scss
- src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.tsx
- src/components/sbb-form-field/sbb-form-field.stories.jsx
- src/components/sbb-tooltip-trigger/sbb-tooltip-trigger.scss
- src/global/styles/mixins/buttons.scss
This PR Closes [#1683](https://github.com/lyne-design-system/lyne-components/issues/1683)
-Make `sbb-button` use correct styling when inside `sbb-form-field`
> feat(sbb-button): sbb-form-field integration

- src/global/styles/mixins/lists.scss
> fix(styles): exclude other elements than paragraph for gap in lists

- src/components.d.ts
- src/components/sbb-datepicker-toggle/readme.md
- src/components/sbb-datepicker-toggle/sbb-datepicker-toggle.e2e.ts
- src/components/sbb-datepicker-toggle/sbb-datepicker-toggle.tsx
This PR Closes [#1754](https://github.com/lyne-design-system/lyne-components/issues/1754)
-
> feat(sbb-datepicker-toggle): allow opening calendar programmatically

- src/global/helpers/eventing/input-modality-detector.ts
> fix: set most recent input modality initial value

- src/components/sbb-checkbox-group/sbb-checkbox-group.tsx
- src/components/sbb-radio-button-group/sbb-radio-button-group.stories.jsx
- src/components/sbb-radio-button-group/sbb-radio-button-group.tsx
- src/components/sbb-selection-panel/sbb-selection-panel.e2e.ts
- src/components/sbb-selection-panel/sbb-selection-panel.stories.jsx
> fix(sbb-selection-panel): allow nested checkbox and radio groups

- src/components/sbb-datepicker-next-day/sbb-datepicker-next-day.e2e.ts
- src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.e2e.ts
- src/components/sbb-datepicker/sbb-datepicker.e2e.ts
- src/components/sbb-datepicker/sbb-datepicker.tsx
This PR Closes [#1753](https://github.com/lyne-design-system/lyne-components/issues/1753)
-
> feat(sbb-datepicker): parse ISO dates

- src/components/sbb-header-action/readme.md
fixed typos in the readme.md-file.
fixed typo in readme.md file (sbb-header-action)
> docs(sbb-header-action): fix component name in readme.md

- src/components.d.ts
- src/components/sbb-divider/readme.md
- src/components/sbb-journey-header/sbb-journey-header.scss
- src/components/sbb-journey-header/sbb-journey-header.spec.ts
- src/components/sbb-journey-header/sbb-journey-header.tsx
- src/components/sbb-journey-summary/readme.md
- src/components/sbb-journey-summary/sbb-journey-summary.scss
- src/components/sbb-journey-summary/sbb-journey-summary.spec.ts
- src/components/sbb-journey-summary/sbb-journey-summary.stories.jsx
- src/components/sbb-journey-summary/sbb-journey-summary.tsx
- src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.scss
- added additional prop and capabilites to display a roundtrip
> feat(sbb-journey-summary): add additional prop to display round trip

- src/components/sbb-menu/sbb-menu.scss
- src/components/sbb-tooltip/sbb-tooltip.scss
- src/components/sbb-tooltip/sbb-tooltip.stories.jsx
This PR Closes #1782 
Fixed the positioning of the sbb-menu and sbb-tooltip overlays when the right-to-left direction is enabled
> fix(sbb-menu,sbb-tooltip): fix overlay position when direction="rtl"

- src/components.d.ts
- src/components/sbb-menu/readme.md
- src/components/sbb-menu/sbb-menu.scss
- src/components/sbb-menu/sbb-menu.spec.ts
- src/components/sbb-menu/sbb-menu.stories.tsx
- src/components/sbb-menu/sbb-menu.tsx
- src/storybook/pages/home/home--logged-in.stories.tsx
- src/storybook/pages/home/home.stories.tsx
This PR Closes #1766 
- Use `ul` an `li` in to list actions in menus that only contain sbb-menu-action
- Use aria-pressed in menu in cases where it's used as a select
- allow arrow keys navigation in sbb-menu
> feat(sbb-menu): improve accessibility

- src/components/sbb-dialog/sbb-dialog.tsx
- src/components/sbb-navigation-section/readme.md
- src/components/sbb-navigation-section/sbb-navigation-section.e2e.ts
- src/components/sbb-navigation-section/sbb-navigation-section.scss
- src/components/sbb-navigation-section/sbb-navigation-section.tsx
- src/components/sbb-navigation/readme.md
- src/components/sbb-navigation/sbb-navigation.tsx
- src/global/helpers/focus.ts
- src/storybook/pages/home/home.common.tsx
> fix(sbb-navigation): add accessibility recommendations and fix focus order

- src/components/sbb-time-input/sbb-time-input.e2e.ts
- src/components/sbb-time-input/sbb-time-input.tsx
> fix(sbb-time-input): resolve backspace bug

- src/components/sbb-option/sbb-option.tsx
- src/components/sbb-radio-button/sbb-radio-button.tsx
This PR Closes #1798 
- a new logic that checks attributes on the parent of the sbb-option and sbb-radio-button has been added, similar to the one in the sbb-select; this has been done in order to avoid flickering on the component due attribute changes.
> fix: change first loading logic for proxied parameters

- src/components/sbb-timetable-row/sbb-timetable-row.tsx
> fix(sbb-timetable-row): stringify accessibilityExpanded prop

- src/components/sbb-calendar/sbb-calendar.scss
- src/components/sbb-calendar/sbb-calendar.spec.ts
- src/components/sbb-calendar/sbb-calendar.tsx
> fix(sbb-calendar): calendar animation glitch

- src/components.d.ts
- src/components/sbb-selection-panel/readme.md
- src/components/sbb-selection-panel/sbb-selection-panel.scss
- src/components/sbb-selection-panel/sbb-selection-panel.stories.tsx
- src/components/sbb-selection-panel/sbb-selection-panel.tsx
> feat(sbb-selection-panel): add borderless variant

- src/components.d.ts
- src/components/sbb-tag-group/readme.md
- src/components/sbb-tag-group/sbb-tag-group.scss
- src/components/sbb-tag-group/sbb-tag-group.spec.ts
- src/components/sbb-tag-group/sbb-tag-group.stories.tsx
- src/components/sbb-tag-group/sbb-tag-group.tsx
This PR Closes #1839 
- render tags into `<ul>` element 
> feat(sbb-tag-group): use list to display tags

- src/components/sbb-navigation-action/sbb-navigation-action.scss
> fix(sbb-navigation): fix word break

- src/components/sbb-datepicker-next-day/sbb-datepicker-next-day.e2e.ts
- src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.e2e.ts
- src/components/sbb-datepicker-toggle/sbb-datepicker-toggle.e2e.ts
- src/components/sbb-datepicker/readme.md
- src/components/sbb-datepicker/sbb-datepicker.e2e.ts
- src/components/sbb-datepicker/sbb-datepicker.tsx
- src/components/sbb-form-field/readme.md
- src/components/sbb-form-field/sbb-form-field.tsx
- src/global/helpers/native-date-adapter.ts
This PR Closes #1859 #1851 
- Datepicker now fires a blur event when value is changed programmatically, to ensure compatibility with frameworks that rely on that event to validate state
- Datepicker now displays error state in case of incorrectly formatted dates (without using user-reserved class `.sbb-invalid`)
- It's possible to add `data-sbb-invalid` to an input inside a `sbb-form-field` to display error state for internal use 
> fix(sbb-datepicker): empty month bug, improve error validation, add blur event

- src/components/sbb-menu/sbb-menu.tsx
> fix(sbb-menu): menu actions arrow navigation

- src/components/sbb-skiplink-list/sbb-skiplink-list.e2e.ts
- src/components/sbb-skiplink-list/sbb-skiplink-list.spec.ts
- src/components/sbb-skiplink-list/sbb-skiplink-list.tsx
> fix(sbb-skiplink-list): detect links which were added after connected

- src/components.d.ts
- src/components/sbb-form-field/readme.md
- src/components/sbb-form-field/sbb-form-field.e2e.ts
- src/components/sbb-form-field/sbb-form-field.tsx
- src/components/sbb-select/sbb-select.custom.d.ts
- src/components/sbb-select/sbb-select.events.ts
- src/components/sbb-select/sbb-select.tsx
> fix(sbb-form-field): fix floating label on form reset

- src/components/sbb-alert/readme.md
- src/components/sbb-alert/sbb-alert.scss
- src/components/sbb-alert/sbb-alert.spec.ts
- src/components/sbb-alert/sbb-alert.tsx
- src/components/sbb-divider/readme.md
- src/components/sbb-notification/sbb-notification.scss
> refactor(sbb-alert): implement new design specs

- src/components.d.ts
- src/components/sbb-datepicker-next-day/sbb-datepicker-next-day.e2e.ts
- src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.e2e.ts
- src/components/sbb-datepicker-toggle/sbb-datepicker-toggle.e2e.ts
- src/components/sbb-datepicker/readme.md
- src/components/sbb-datepicker/sbb-datepicker.e2e.ts
- src/components/sbb-datepicker/sbb-datepicker.stories.tsx
- src/components/sbb-datepicker/sbb-datepicker.tsx
- src/global/config.ts
- src/global/datetime/date-adapter.ts
- src/global/datetime/native-date-adapter.spec.ts
- src/global/datetime/native-date-adapter.ts
This PR Closes #1869 #1870 #1906 
- Add format property to datepicker component
- Add dateParser property to datepicker component
> feat(sbb-datepicker): allow custom date formats

- src/components/sbb-dialog/sbb-dialog.e2e.ts
- src/components/sbb-dialog/sbb-dialog.tsx
- src/storybook/pages/home/home--logged-in.stories.tsx
> fix(sbb-dialog): close stacked dialogs one by one on ESC press

- src/components/sbb-datepicker/readme.md
- src/components/sbb-datepicker/sbb-datepicker.stories.tsx
- Improve docs on datepicker
- [] Documentation content changes
> docs(sbb-datepicker): improve docs on how to use format and dateParser functions

- src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.spec.ts
- src/components/sbb-pearl-chain-time/sbb-pearl-chain-time.tsx
- src/components/sbb-timetable-row/sbb-timetable-row.helper.tsx
- src/components/sbb-timetable-row/sbb-timetable-row.spec.ts
- src/components/sbb-timetable-row/sbb-timetable-row.tsx
- src/global/i18n.ts
- src/global/timetable/access-leg-helper.spec.ts
> feat(sbb-timetable-row): reorder sr-text

- src/components/sbb-breadcrumb-group/sbb-breadcrumb-group.e2e.ts
- src/components/sbb-calendar/readme.md
- src/components/sbb-calendar/sbb-calendar.spec.ts
- src/components/sbb-calendar/sbb-calendar.tsx
> fix(sbb-calendar): adding `aria-current='date'` to current date

- src/components/sbb-datepicker/sbb-datepicker.e2e.ts
- src/components/sbb-datepicker/sbb-datepicker.scss
- src/components/sbb-datepicker/sbb-datepicker.spec.ts
- src/components/sbb-datepicker/sbb-datepicker.tsx
- src/components/sbb-notification/sbb-notification.scss
- src/global/i18n.ts
> fix(sbb-datepicker): add accessibility label and localize date

- src/components/sbb-notification/sbb-notification.scss
- src/components/sbb-notification/sbb-notification.stories.tsx
> fix(sbb-notification): handle stories disableAnimation correctly

- src/components/sbb-alert/sbb-alert.scss
- src/components/sbb-notification/sbb-notification.scss
> fix(sbb-notification, sbb-alert): update zero to micro breakpoint styles

- src/components.d.ts
- src/components/sbb-datepicker-next-day/readme.md
- src/components/sbb-datepicker-next-day/sbb-datepicker-next-day.e2e.ts
- src/components/sbb-datepicker-next-day/sbb-datepicker-next-day.spec.ts
- src/components/sbb-datepicker-next-day/sbb-datepicker-next-day.tsx
- src/components/sbb-datepicker-previous-day/readme.md
- src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.e2e.ts
- src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.spec.ts
- src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.tsx
- src/global/styles/mixins/buttons.scss
This PR Closes #1892 
- switch from component property to dataset attribute to implement arrows disabling mechanism 
> fix(sbb-datepicker): remove disable property from next and previous day

- react-library/src/components/stencil-generated/index.ts
- src/components.d.ts
- src/components/sbb-no-results/readme.md
- src/components/sbb-no-results/sbb-no-results.e2e.ts
- src/components/sbb-no-results/sbb-no-results.scss
- src/components/sbb-no-results/sbb-no-results.spec.ts
- src/components/sbb-no-results/sbb-no-results.stories.tsx
- src/components/sbb-no-results/sbb-no-results.tsx
- src/components/sbb-title/readme.md
This PR Closes #1927 
- Implement sbb-no-results component
> feat(sbb-no-results): first implementation

- src/components/sbb-no-results/sbb-no-results.spec.ts
- src/components/sbb-no-results/sbb-no-results.tsx
Address @jeripeierSBB 's comments
> refactor(sbb-no-results): improve slot handling

- src/components/sbb-notification/sbb-notification.tsx
Refactor the `resizeDisableAnimation` with the dataset API.
> refactor: use dataset API for `resizeDisableAnimation`

- src/components/sbb-datepicker-next-day/sbb-datepicker-next-day.spec.ts
- src/components/sbb-datepicker-next-day/sbb-datepicker-next-day.stories.tsx
- src/components/sbb-datepicker-next-day/sbb-datepicker-next-day.tsx
- src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.spec.ts
- src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.stories.tsx
- src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.tsx
- src/global/i18n.ts
> fix(sbb-datepicker): datepicker prev and next day buttons aria-label

- src/components/sbb-dialog/sbb-dialog.tsx
> fix(sbb-dialog): react to slot changes

- .github/workflows/continuous-integration.yml
Increase memory from 4GB to 6GB for test execution
> build: increase test execution memory

- src/components/sbb-form-field/sbb-form-field.e2e.ts
- src/components/sbb-form-field/sbb-form-field.tsx
- src/components/sbb-select/sbb-select.tsx
> fix(sbb-select): fix focused styles

- src/components/sbb-checkbox/sbb-checkbox.scss
- src/components/sbb-form-field/sbb-form-field.scss
- src/components/sbb-option/sbb-option.scss
- src/components/sbb-option/sbb-option.stories.tsx
- src/components/sbb-radio-button/sbb-radio-button.scss
- src/components/sbb-selection-panel/sbb-selection-panel.scss
- src/components/sbb-slider/sbb-slider.scss
- src/components/sbb-tag/sbb-tag.scss
- src/components/sbb-toggle-check/sbb-toggle-check.scss
- src/components/sbb-toggle-option/sbb-toggle-option.scss
- src/components/sbb-toggle/sbb-toggle.scss
- src/components/sbb-visual-checkbox/sbb-visual-checkbox.scss
- src/components/sbb-visual-checkbox/sbb-visual-checkbox.stories.tsx
- src/global/styles/typography.scss
Closes #1955 
The following disabled states were adapted to the new design:
- Checkbox
- Form field (Text input / time input)
- Option (Select / Autocomplete)
- Radio button
- Selection Panel
- Slider
- Tag
- Toggle Check
- Toggle / Toggle Option
> fix(multiple): disabled states

- src/components/sbb-timetable-row/sbb-timetable-row.helper.tsx
> fix(sbb-timetable-row): add space for certain vehicles

- src/components.d.ts
- src/components/sbb-calendar/readme.md
- src/components/sbb-calendar/sbb-calendar.custom.d.ts
- src/components/sbb-calendar/sbb-calendar.e2e.ts
- src/components/sbb-calendar/sbb-calendar.scss
- src/components/sbb-calendar/sbb-calendar.spec.ts
- src/components/sbb-calendar/sbb-calendar.stories.tsx
- src/components/sbb-calendar/sbb-calendar.tsx
- src/components/sbb-datepicker-next-day/sbb-datepicker-next-day.scss
- src/components/sbb-datepicker-previous-day/sbb-datepicker-previous-day.scss
- src/components/sbb-datepicker-toggle/readme.md
- src/components/sbb-datepicker-toggle/sbb-datepicker-toggle.scss
- src/components/sbb-datepicker-toggle/sbb-datepicker-toggle.tsx
- src/components/sbb-datepicker/sbb-datepicker.stories.tsx
- src/components/sbb-icon/readme.md
- src/global/datetime/date-adapter.ts
- src/global/datetime/native-date-adapter.spec.ts
- src/global/datetime/native-date-adapter.ts
- src/global/i18n.ts
This PR Closes #1883 
- opening the sbb-calendar, it's now possible to go to the year selection view and then to the month selection view by clicking on the month label
> feat(sbb-calendar): add year and month selection views

- ci/lit-migration.mts
- package.json
- src/components/sbb-icon/index.ts
- src/components/sbb-icon/sbb-icon-validate.spec.ts
- src/components/sbb-icon/sbb-icon.e2e.ts
- src/components/sbb-icon/sbb-icon.spec.ts
- src/components/sbb-icon/sbb-icon.stories.tsx
- src/components/sbb-icon/sbb-icon.tsx
- src/global/testing/jest-setup.ts
- web-test-runner.config.js
- yarn.lock
> refactor(sbb-icon): lit migration

- ci/lit-migration.mts
> fix: add CSSResult import and type

- src/components/sbb-chip/index.ts
- src/components/sbb-chip/sbb-chip.e2e.ts
- src/components/sbb-chip/sbb-chip.spec.ts
- src/components/sbb-chip/sbb-chip.stories.tsx
- src/components/sbb-chip/sbb-chip.tsx
- sbb-chip component has been migrated to Lit
> refactor: sbb-chip migration

- src/components/sbb-divider/index.ts
- src/components/sbb-divider/sbb-divider.custom.d.ts
- src/components/sbb-divider/sbb-divider.e2e.ts
- src/components/sbb-divider/sbb-divider.spec.ts
- src/components/sbb-divider/sbb-divider.stories.tsx
- src/components/sbb-divider/sbb-divider.tsx
> refactor: sbb-divider migration

- src/components/sbb-selection-panel/sbb-selection-panel.e2e.ts
- src/components/sbb-selection-panel/sbb-selection-panel.scss
- src/components/sbb-selection-panel/sbb-selection-panel.spec.ts
- src/components/sbb-selection-panel/sbb-selection-panel.tsx
> fix(sbb-selection-panel): content overflowing the panel

- ci/lit-migration.mts
- src/components/sbb-form-error/index.ts
- src/components/sbb-form-error/sbb-form-error.e2e.ts
- src/components/sbb-form-error/sbb-form-error.spec.ts
- src/components/sbb-form-error/sbb-form-error.stories.tsx
- src/components/sbb-form-error/sbb-form-error.tsx
- src/components/sbb-form-field-clear/index.ts
- src/components/sbb-form-field-clear/sbb-form-field-clear.e2e.ts
- src/components/sbb-form-field-clear/sbb-form-field-clear.spec.ts
- src/components/sbb-form-field-clear/sbb-form-field-clear.stories.tsx
- src/components/sbb-form-field-clear/sbb-form-field-clear.tsx
- src/components/sbb-form-field/index.ts
- src/components/sbb-form-field/sbb-form-field.custom.d.ts
- src/components/sbb-form-field/sbb-form-field.e2e.ts
- src/components/sbb-form-field/sbb-form-field.spec.ts
- src/components/sbb-form-field/sbb-form-field.stories.tsx
- src/components/sbb-form-field/sbb-form-field.tsx
- src/global/testing/wait-for-condition.ts
- web-test-runner.config.js
- sbb-form-field lit migration
- sbb-form-error lit migration
- sbb-form-clear lit migration
> refactor(sbb-form-field): lit migration

- src/components/sbb-visual-checkbox/index.ts
- src/components/sbb-visual-checkbox/sbb-visual-checkbox.e2e.ts
- src/components/sbb-visual-checkbox/sbb-visual-checkbox.spec.ts
- src/components/sbb-visual-checkbox/sbb-visual-checkbox.stories.tsx
- src/components/sbb-visual-checkbox/sbb-visual-checkbox.tsx
- sbb-visual-checkbox migrated to Lit
> refactor: sbb-visual-checkbox migration

- src/global/a11y/input-modality-detector.ts
- src/global/testing/test-setup.ts
- web-test-runner.config.js
Added and configured a global test setup
> test(test-runner): add test global setup

- src/components/sbb-toggle-option/index.ts
- src/components/sbb-toggle-option/sbb-toggle-option.e2e.ts
- src/components/sbb-toggle-option/sbb-toggle-option.spec.ts
- src/components/sbb-toggle-option/sbb-toggle-option.stories.tsx
- src/components/sbb-toggle-option/sbb-toggle-option.tsx
- src/components/sbb-toggle/index.ts
- src/components/sbb-toggle/sbb-toggle.e2e.ts
- src/components/sbb-toggle/sbb-toggle.spec.ts
- src/components/sbb-toggle/sbb-toggle.stories.tsx
- src/components/sbb-toggle/sbb-toggle.tsx
- Migrate `sbb-toggle` and `sbb-toggle-option`
> refactor: migrate toggle and toggle-option

- src/components/sbb-toggle-check/index.ts
- src/components/sbb-toggle-check/sbb-toggle-check.e2e.ts
- src/components/sbb-toggle-check/sbb-toggle-check.spec.ts
- src/components/sbb-toggle-check/sbb-toggle-check.stories.tsx
- src/components/sbb-toggle-check/sbb-toggle-check.tsx
> refactor: migrate toggle-check

- src/components.d.ts
- src/components/sbb-dialog/readme.md
- src/components/sbb-dialog/sbb-dialog.e2e.ts
- src/components/sbb-dialog/sbb-dialog.stories.tsx
- src/components/sbb-dialog/sbb-dialog.tsx
> feat(sbb-dialog): add backdropAction property

- src/components/sbb-autocomplete/sbb-autocomplete.stories.tsx
- src/components/sbb-datepicker-toggle/sbb-datepicker-toggle.stories.tsx
- src/components/sbb-datepicker/sbb-datepicker.stories.tsx
- src/components/sbb-dialog/sbb-dialog.stories.tsx
- src/components/sbb-header/sbb-header.stories.tsx
- src/components/sbb-image/sbb-image.e2e.ts
- src/components/sbb-menu/sbb-menu.stories.tsx
- src/components/sbb-select/sbb-select.stories.tsx
- src/components/sbb-skiplink-list/sbb-skiplink-list.stories.tsx
- src/components/sbb-tooltip/sbb-tooltip.stories.tsx
- src/global/testing/index.ts
- vite.config.ts
- web-test-runner.config.js
This PR further optimizes build and test configuration.
> build: optimize test configuration

- src/components/sbb-selection-panel/sbb-selection-panel.scss
- src/components/sbb-selection-panel/sbb-selection-panel.stories.tsx
> fix(sbb-selection-panel): panel content overflow

- src/components/sbb-expansion-panel/sbb-expansion-panel.scss
- src/components/sbb-expansion-panel/sbb-expansion-panel.spec.ts
- src/components/sbb-expansion-panel/sbb-expansion-panel.tsx
Refactor `sbb-expansion-panel` animation.
> refactor(sbb-expansion-panel): improve expansion animation

- src/components/sbb-card-action/index.ts
- src/components/sbb-card-action/sbb-card-action.e2e.ts
- src/components/sbb-card-action/sbb-card-action.stories.tsx
- src/components/sbb-card-action/sbb-card-action.tsx
- src/components/sbb-card-badge/index.ts
- src/components/sbb-card-badge/sbb-card-badge.e2e.ts
- src/components/sbb-card-badge/sbb-card-badge.spec.ts
- src/components/sbb-card-badge/sbb-card-badge.stories.tsx
- src/components/sbb-card-badge/sbb-card-badge.tsx
- src/components/sbb-card/index.ts
- src/components/sbb-card/sbb-card.e2e.ts
- src/components/sbb-card/sbb-card.spec.ts
- src/components/sbb-card/sbb-card.stories.tsx
- src/components/sbb-card/sbb-card.tsx
Migrate `sbb-card`, `sbb-card-badge` and `sbb-card-action` to Lit.
> refactor(sbb-card): lit migration

- src/components/sbb-checkbox-group/index.ts
- src/components/sbb-checkbox-group/sbb-checkbox-group.e2e.ts
- src/components/sbb-checkbox-group/sbb-checkbox-group.spec.ts
- src/components/sbb-checkbox-group/sbb-checkbox-group.stories.tsx
- src/components/sbb-checkbox-group/sbb-checkbox-group.tsx
- src/components/sbb-checkbox/index.ts
- src/components/sbb-checkbox/sbb-checkbox.e2e.ts
- src/components/sbb-checkbox/sbb-checkbox.spec.ts
- src/components/sbb-checkbox/sbb-checkbox.stories.tsx
- src/components/sbb-checkbox/sbb-checkbox.tsx
- sbb-checkbox migrated to Lit
- sbb-checkbox-group migrated to Lit
> refactor(sbb-checkbox, sbb-checkbox-group): migration to Lit

- src/components/sbb-timetable-row/sbb-timetable-row.spec.ts
- src/components/sbb-timetable-row/sbb-timetable-row.tsx
- src/global/i18n.ts
> fix(sbb-timetable-row): fix a11y

- src/components/sbb-map-container/index.ts
- src/components/sbb-map-container/sbb-map-container.e2e.ts
- src/components/sbb-map-container/sbb-map-container.spec.ts
- src/components/sbb-map-container/sbb-map-container.stories.tsx
- src/components/sbb-map-container/sbb-map-container.tsx
Migrate `sbb-map-container` to Lit.
> refactor(sbb-map-container): lit migration

- src/components/sbb-loading-indicator/index.ts
- src/components/sbb-loading-indicator/sbb-loading-indicator.e2e.ts
- src/components/sbb-loading-indicator/sbb-loading-indicator.spec.ts
- src/components/sbb-loading-indicator/sbb-loading-indicator.stories.tsx
- src/components/sbb-loading-indicator/sbb-loading-indicator.tsx
Migrate `sbb-loading-indicator` to Lit.
> refactor(sbb-loading-indicator): lit migration

- src/components/sbb-dialog/sbb-dialog.tsx
- src/components/sbb-menu/sbb-menu.tsx
- src/components/sbb-navigation/sbb-navigation.tsx
- src/components/sbb-tooltip/sbb-tooltip.tsx
- src/global/overlay/overlay.tsx
- src/storybook/pages/home/home--logged-in.stories.tsx
Implements a manual inert to every element except the overlay itself to improve accessibility.
> fix: implement overlays inert mechanism

- src/components/sbb-slider/index.ts
- src/components/sbb-slider/sbb-slider.e2e.ts
- src/components/sbb-slider/sbb-slider.spec.ts
- src/components/sbb-slider/sbb-slider.stories.tsx
- src/components/sbb-slider/sbb-slider.tsx
> refactor(sbb-slider): lit migration

- src/global/styles/typography.scss
> fix(sbb-skiplink-list): avoid rendering before defined

- web-test-runner.config.js
This PR adds a custom test reporter that prints each passed test as a dot and each failed or skipped test as a red x.
At the end, it reports amount of test suites, tests, passed, failed and skipped amount and additionally reports errors.
> build: use custom test reporter

- src/storybook/pages/home/home--logged-in.stories.tsx
- src/storybook/pages/home/home.common.tsx
- src/storybook/pages/home/home.stories.tsx
- src/storybook/styles/layout/layout.stories.tsx
- src/storybook/styles/list/list.stories.tsx
- src/storybook/styles/scrollbar/scrollbar.stories.tsx
- src/storybook/styles/typography/typography.stories.tsx
The build will be ok once the skiplink will be merged
> refactor(home, styles): lit migration (Waiting for skiplink migration)

- .prettierignore
- tools/generate-component/boilerplate/component.e2e.ts
- tools/generate-component/boilerplate/component.spec.ts
- tools/generate-component/boilerplate/component.stories.tsx
- tools/generate-component/boilerplate/component.ts
- tools/generate-component/index.mts
- generate script has been improved
> fix: fix paths in generate script

- src/components/checkbox/checkbox/checkbox.ts
- src/components/radio-button/radio-button-group/radio-button-group.ts
- src/components/radio-button/radio-button-group/readme.md
- src/components/radio-button/radio-button/radio-button.ts
- src/components/selection-panel/selection-panel.spec.ts
- src/components/selection-panel/selection-panel.ts
> fix(sbb-selection-panel): state and value initialization

- src/components/checkbox/checkbox-group/checkbox-group.ts
- src/components/checkbox/checkbox/checkbox.ts
- src/components/radio-button/radio-button-group/radio-button-group.ts
- src/components/radio-button/radio-button/radio-button.ts
- src/components/selection-panel/selection-panel.e2e.ts
Fix cherry-pick for `sbb-radio-button-group` and `sbb-checkbox-group`.
> fix(sbb-radio-button-group, sbb-checkbox-group): radio and checkbox group state update

- src/components/selection-panel/selection-panel.scss
- src/components/selection-panel/selection-panel.stories.tsx
Fix border color when the selection panel has no content, is checked and is disabled.
> fix(sbb-selection-panel): disabled border color when checked

- src/components/core/interfaces/link-button-properties.ts
- src/components/datepicker/datepicker/datepicker.ts
- src/components/form-field/form-field/form-field.e2e.ts
- src/components/icon/icon-request.ts
- src/components/link-list/__snapshots__/link-list.spec.snap.js
- src/components/link-list/link-list.spec.ts
- src/components/select/select.e2e.ts
- src/components/select/select.ts
- src/components/time-input/time-input.ts
> refactor: resolve todos

- src/components/select/select.e2e.ts
Fix a flickey test on `sbb-select` caused by the recent ssr fixes
> fix(select): enhance test robustness

- src/components/autocomplete/autocomplete.e2e.ts
- src/components/autocomplete/autocomplete.ts
- src/components/autocomplete/readme.md
- src/components/dialog/dialog.e2e.ts
- src/components/dialog/dialog.ts
- src/components/dialog/readme.md
- src/components/menu/menu/menu.e2e.ts
- src/components/menu/menu/menu.ts
- src/components/menu/menu/readme.md
- src/components/navigation/navigation/navigation.e2e.ts
- src/components/navigation/navigation/navigation.ts
- src/components/navigation/navigation/readme.md
- src/components/select/readme.md
- src/components/select/select.e2e.ts
- src/components/select/select.ts
- src/components/toast/readme.md
- src/components/toast/toast.e2e.ts
- src/components/toast/toast.ts
- src/components/tooltip/tooltip/readme.md
- src/components/tooltip/tooltip/tooltip.e2e.ts
- src/components/tooltip/tooltip/tooltip.ts
This PR Closes #2118 
- `will-open` and `will-close` events are now cancellable
> feat(overlays): provide option to cancel 'willClose' and 'willOpen' events

- src/components/radio-button/radio-button-group/radio-button-group.ts
- src/components/selection-panel/selection-panel.e2e.ts
- src/components/selection-panel/selection-panel.stories.ts
This PR Closes #2188 
- using a `sbb-radio-button-group` within a `sbb-selection-panel`, when a radio-button is selected and an arrow key is pressed, the previous/next is focused and selected instead than only focused.
> fix(sbb-selection-panel): arrow navigation with radio-button-group should select the radio-button

- src/components/autocomplete/autocomplete.ts
- src/components/core/overlay/overlay-option-panel.ts
- src/components/core/overlay/position.spec.ts
- src/components/core/overlay/position.ts
- src/components/menu/menu/menu.ts
- src/components/select/select.ts
- src/components/tooltip/tooltip/tooltip.ts
> fix: fix overlay positioning when virtual keyboard is present

- src/components/status/__snapshots__/status.spec.snap.js
- src/components/status/readme.md
- src/components/status/status.e2e.ts
- src/components/status/status.scss
- src/components/status/status.spec.ts
- src/components/status/status.stories.ts
- src/components/status/status.ts
This PR Closes #1932 
- added new `sbb-status` component
> feat(sbb-status): component implementation

- src/components/toggle/toggle/toggle.ts
> fix(sbb-toggle): initial animation glitch

- package.json
- src/components/core/styles/core/mediaqueries.scss
- src/components/vite.config.ts
- web-test-runner.config.js
- yarn.lock
Closes #2307
https://webpack.js.org/loaders/sass-loader/#resolving-import-at-rules
> fix: adopt sass import guidelines

- src/components/autocomplete/autocomplete.stories.ts
- src/components/checkbox/checkbox-group/checkbox-group.stories.ts
- src/components/file-selector/file-selector.stories.ts
- src/components/form-field/form-field/form-field.stories.ts
- src/components/loading-indicator/loading-indicator.stories.ts
- src/components/option/optgroup/optgroup.stories.ts
- src/components/option/option/option.stories.ts
- src/components/select/select.stories.ts
- src/components/selection-panel/selection-panel.stories.ts
- src/components/slider/slider.stories.ts
- src/components/tag/tag-group/tag-group.stories.ts
- src/components/toast/toast.stories.ts
> docs: removed global 'document' references from stories

- src/components/journey-summary/journey-summary.stories.ts
> feat: update journey-summary storybook title

- src/components/checkbox/checkbox/checkbox.scss
- src/components/radio-button/radio-button/radio-button.scss
This PR Closes #2384 
- Changed the color of `disabled` labels in `checkbox, radio-button and selection-panel`
> style(checkbox, radio-button): changed label disabled color

- src/components/calendar/calendar.e2e.ts
- src/components/calendar/calendar.scss
- src/components/calendar/calendar.ts
- src/components/datepicker/datepicker-toggle/datepicker-toggle.ts
- src/components/datepicker/datepicker/datepicker.ts
This PR Closes #2300 
- Fix focus loss during keyboard navigation
- Fix data-now="" being incorrectly interpreted as "Jan 1, 1970"
> fix(sbb-calendar): using keyboard navigation loses focus

- .github/workflows/continuous-integration.yml
- .storybook/main.ts
- package.json
- yarn.lock
I have to enable turbosnap on main to effectively test the use cases on another branch. 
These changes do not have any effect and will be reverted if we decide not to move forward with Turbosnap
> chore: enable turbosnap

- src/components/container/container/container.scss
- src/components/container/container/readme.md
> fix(sbb-container): container causes interference with overlay components

- src/components/status/__snapshots__/status.spec.snap.js
- src/components/status/readme.md
- src/components/status/status.scss
- src/components/status/status.stories.ts
- src/components/status/status.ts
> feat(sbb-status): allow custom icons

- src/components/container/container/container.scss
> fix(sbb-container): remove overflowing margin without using overflow

- src/components/image/image.scss
- src/components/image/image.ts
- src/components/teaser-hero/teaser-hero.stories.ts
- src/components/teaser-paid/__snapshots__/teaser-paid.spec.snap.js
- src/components/teaser-paid/readme.md
- src/components/teaser-paid/teaser-paid.e2e.ts
- src/components/teaser-paid/teaser-paid.scss
- src/components/teaser-paid/teaser-paid.spec.ts
- src/components/teaser-paid/teaser-paid.stories.ts
- src/components/teaser-paid/teaser-paid.ts
This PR Closes #2331 
- First implementation of `sbb-teaser-paid`
> feat(sbb-teaser-paid): first implementation

- src/components/teaser/teaser.scss
- src/components/teaser/teaser.stories.ts
> fix(sbb-teaser): prevent overlapping chip if including long content

- src/components/selection-panel/selection-panel.scss
> feat(sbb-selection-panel): increase border width for active state

- src/components/navigation/navigation-section/__snapshots__/navigation-section.spec.snap.js
- src/components/navigation/navigation-section/navigation-section.scss
- src/components/navigation/navigation-section/navigation-section.ts
- src/components/navigation/navigation/navigation.stories.ts
> feat(sbb-navigation): remove navigation section divider

- src/components/navigation/navigation-section/navigation-section.ts
- src/components/navigation/navigation/navigation.e2e.ts
- src/components/navigation/navigation/navigation.stories.ts
- src/components/navigation/navigation/navigation.ts
- src/storybook/pages/home/home.common.ts
> fix(sbb-navigation): fix active and focus handling

- src/components/button/common/button-common.ts
- src/components/button/common/index.ts
> fix: fix unresolved sass imports

- src/components/status/status.scss
> fix(sbb-status): fix flex behavior in Firefox

- src/components/navigation/common/navigation-action-common.ts
- src/components/navigation/common/navigation-action.scss
- src/components/navigation/navigation-button/navigation-button.spec.ts
- src/components/navigation/navigation-link/navigation-link.spec.ts
- src/components/navigation/navigation-section/navigation-section.ts
- src/components/navigation/navigation/navigation.scss
- src/components/navigation/navigation/navigation.ts
- src/components/notification/notification.ts
- Adds a dash icon next to the active navigation actions in the section. 
- Fixes the active and reset mechanism of the markers no open/close.
- Disables animation on resize.
> fix(sbb-navigation): fix navigation actions contrast ratio

- package.json
- src/components/button/common/button-common.scss
- src/components/form-error/form-error.scss
- src/components/form-field/form-field/form-field.scss
- src/components/header/common/header-action.scss
- src/components/menu/menu/menu.e2e.ts
- src/components/popover/popover/popover.e2e.ts
- src/components/train/train-blocked-passage/train-blocked-passage.scss
- src/components/train/train-formation/train-formation.scss
- yarn.lock
- update of lyne-design-tokens to version 0.5.0
- update of tokens usage
> feat: update tokens

- src/components/button/button-link/button-link.stories.ts
- src/components/button/button-static/button-static.stories.ts
- src/components/button/button/button.stories.ts
- src/components/button/common/button-common.scss
- src/components/button/common/button-common.ts
- src/components/button/common/common-stories.ts
- src/components/button/secondary-button-link/secondary-button-link.stories.ts
- src/components/button/secondary-button-static/secondary-button-static.stories.ts
- src/components/button/secondary-button/secondary-button.stories.ts
- src/components/button/tertiary-button-link/tertiary-button-link.stories.ts
- src/components/button/tertiary-button-static/tertiary-button-static.stories.ts
- src/components/button/tertiary-button/tertiary-button.stories.ts
- src/components/button/transparent-button-link/transparent-button-link.stories.ts
- src/components/button/transparent-button-static/transparent-button-static.stories.ts
- src/components/button/transparent-button/transparent-button.stories.ts
> feat(button): implemented size 'S'

- tools/manifest/custom-elements-manifest.config.js
This PR fixes the remaining mistaken imports in the React package.
> fix: adapt react package import paths missed during migration

- src/components/accordion/__snapshots__/accordion.spec.snap.js
- src/components/accordion/accordion.e2e.ts
- src/components/accordion/accordion.stories.ts
- src/components/accordion/accordion.ts
- src/components/accordion/readme.md
- src/components/expansion-panel/expansion-panel-content/expansion-panel-content.scss
- src/components/expansion-panel/expansion-panel-header/expansion-panel-header.scss
- src/components/expansion-panel/expansion-panel/__snapshots__/expansion-panel.spec.snap.js
- src/components/expansion-panel/expansion-panel/expansion-panel.e2e.ts
- src/components/expansion-panel/expansion-panel/expansion-panel.scss
- src/components/expansion-panel/expansion-panel/expansion-panel.spec.ts
- src/components/expansion-panel/expansion-panel/expansion-panel.stories.ts
- src/components/expansion-panel/expansion-panel/expansion-panel.ts
- src/components/expansion-panel/expansion-panel/readme.md
This PR Closes #2593 
- add size prop for the two components
> feat(sbb-accordion, sbb-expansion-panel): add size s

- src/components/loading-indicator/loading-indicator.scss
- src/components/loading-indicator/loading-indicator.stories.ts
> fix(sbb-loading-indicator): fix sizes of loading indicator

- src/components/dialog/dialog-content/dialog-content.scss
Closes #2635 
needs review of @dauriamarco
> fix(sbb-dialog): show all content if header is always present

- src/components/tabs/tab-group/readme.md
- src/components/tabs/tab-group/tab-group.stories.ts
- src/components/tabs/tab-group/tab-group.ts
- src/components/tabs/tab-title/tab-title.scss
> feat(sbb-tab-group): add size s variant

- src/elements/image/image.ssr.spec.ts
- src/elements/image/image.ts
> fix(sbb-image): render URL correctly with SSR

- src/elements/option/option/option.ssr.spec.ts
- src/elements/option/option/option.ts
> fix(sbb-option): correctly determine highlight state with SSR

- src/elements/dialog/dialog-content/dialog-content.scss
- src/elements/dialog/dialog/dialog.stories.ts
> fix(sbb-dialog): fix dialog-content z-index

- src/elements/calendar/calendar.ts
- src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
- src/elements/datepicker/datepicker/datepicker.ssr.spec.ts
> fix(sbb-datepicker): handle hydration correctly

- src/elements/core/testing/private/describe-viewports.ts
- src/elements/image/image.visual.spec.ts
- src/elements/lead-container/lead-container.visual.spec.ts
This helps to not save space for scrollbars
> test: try taller standard viewport height

- src/elements/header/header/readme.md
> docs(sbb-header): fix url in readme.md

- src/elements/accordion/accordion.ts
- src/elements/accordion/readme.md
> docs(sbb-accordion): fix documentation

- package.json
- tools/web-test-runner/vite-plugin.ts
- yarn.lock
This PR inlines the `koa-connect` functionality, as the logic is fairly simple.
> build: inline koa-connect

- src/elements/form-field/form-field-clear/form-field-clear.ts
- src/elements/form-field/form-field/form-field.ts
> fix(sbb-form-field): ensure input element is detected during hydration

- src/elements/checkbox/common/checkbox-common.spec.ts
- src/elements/core/mixins/form-associated-mixin.ts
> fix(sbb-checkbox, sbb-checkbox-panel): fix visual disabled state after prop change

- tools/generate-component/boilerplate/component.visual.spec.ts
For reviewers:
no idea of what else should be added; a describeEach? specify viewports maybe?
> chore: add visual.spec.ts to boilerplate

- .stylelintrc.json
- src/elements/core/styles/mixins/buttons.scss
- src/elements/core/styles/mixins/pearl-chain-bullet.scss
- yarn.lock
The rule `scss/at-import-partial-extension` was not actually applied and is being replaced by the new `scss/load-partial-extension`.
> style: apply scss extension rule

- src/elements/overlay/overlay.scss
- src/elements/overlay/overlay.ts
> fix(sbb-overlay): add background animation

- src/elements/flip-card/flip-card/flip-card.spec.ts
- src/elements/flip-card/flip-card/flip-card.stories.ts
- src/elements/flip-card/flip-card/flip-card.ts
- src/elements/flip-card/flip-card/readme.md
> feat(sbb-flip-card): add flip event and isFlipped getter

- src/elements/datepicker/datepicker/datepicker.stories.ts
- src/elements/datepicker/datepicker/datepicker.visual.spec.ts
> feat(datepicker): add size s

- src/elements/form-field/form-field/form-field.scss
- src/elements/select/readme.md
- src/elements/select/select.stories.ts
- src/elements/select/select.visual.spec.ts
This PR Closes #2763 
- minor changes to sbb-form-field with size s to support sbb-select
> feat(sbb-select): introduce size s

- src/elements/lead-container/lead-container.scss
- src/elements/lead-container/lead-container.stories.ts
- src/elements/lead-container/lead-container.visual.spec.ts
- src/elements/lead-container/readme.md
> feat(sbb-lead-container): add spacing class support for notification

- src/elements/teaser-product/teaser-product/readme.md
> docs(teaser-product): fixed broken link in documentation

- src/elements/datepicker/datepicker-toggle/datepicker-toggle.spec.ts
- src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
> fix(sbb-datepicker-toggle): fix datepicker toggle empty state synchronization

- src/elements-experimental/pearl-chain/pearl-chain.scss
> fix(sbb-pearl-chain): fix spacing of bullet points

- src/elements/dialog/dialog/dialog.scss
> fix(sbb-dialog): fix resizing flickering

- src/elements/icon/icon.ts
This PR adds svgicon to the observed attributes.
> fix(sbb-icon): ensure sbb-angular compatibility

- tools/vite/package-json-template.ts
> fix: assign correct dependency versions for published packages

- eslint.config.js
- tools/eslint/custom-element-class-name-rule.ts
- tools/eslint/custom-element-decorator-position-rule.ts
- tools/eslint/import-extension-rule.ts
- tools/eslint/index.ts
- tools/eslint/local-name-rule.ts
- tools/eslint/missing-component-documentation-rule.ts
- tools/eslint/needs-super-call-rule.ts
- tools/eslint/property-decorator-accessor-rule.ts
- tools/eslint/test-describe-title-rule.ts
- tools/eslint/test-tabkey-rule.ts
This PR refactors our internal eslint rules to be easier to configure/create.
> build: refactor eslint rules

- src/elements/core/styles/mixins/lists.scss
- src/storybook/styles/list/readme.md
description list -> remove color definition
ul, ol lists -> remove color definition
step list -> add color definitions
Closes #3123
> fix: fix list colors

- docs/GETTING_STARTED.md
> docs: fix SASS link in getting started docs

- src/elements/map-container/map-container.scss
- src/elements/map-container/map-container.visual.spec.ts
> fix(sbb-map-container): improve support for tablet devices

- src/elements/core/base-elements/link-base-element.ts
- src/elements/teaser-product/common/teaser-product-common.scss
- src/elements/teaser-product/common/teaser-product-common.ts
- src/elements/teaser-product/teaser-product-static/__snapshots__/teaser-product-static.snapshot.spec.snap.js
- src/elements/teaser-product/teaser-product/__snapshots__/teaser-product.snapshot.spec.snap.js
- src/elements/teaser-product/teaser-product/teaser-product.scss
- src/elements/teaser-product/teaser-product/teaser-product.stories.ts
- src/elements/teaser-product/teaser-product/teaser-product.ts
- src/elements/teaser/__snapshots__/teaser.snapshot.spec.snap.js
- src/elements/teaser/readme.md
- src/elements/teaser/teaser.scss
- src/elements/teaser/teaser.ts
- src/elements/teaser/teaser.visual.spec.ts
> fix(sbb-teaser, sbb-teaser-product): allow screen readers to navigate the content

- src/elements/core/mixins/form-associated-mixin.ts
- src/elements/core/mixins/form-associated-radio-button-mixin.ts
- src/elements/radio-button/common/radio-button-common.ts
- src/elements/radio-button/radio-button-group/radio-button-group.spec.ts
- src/elements/radio-button/radio-button-group/radio-button-group.ts
- src/elements/radio-button/radio-button-panel/radio-button-panel.ts
- src/elements/radio-button/radio-button/radio-button.spec.ts
> fix(sbb-radio-button-group): sync radios synchronously

- src/elements/autocomplete/autocomplete-base-element.ts
- src/elements/autocomplete/autocomplete.spec.ts
> feat(sbb-autocomplete): opens automatically on new options

- docs/GETTING_STARTED.md
> docs: fix typo in GETTING_STARTED.md

- src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts
> fix(sbb-datepicker-toggle): allow defining slot attribute

- src/elements/datepicker/datepicker-toggle/datepicker-toggle.scss
Reset popover style in datepicker-toggle
> fix(sbb-datepicker-toggle): fix popover style

- eslint.config.js
- src/elements-experimental/pearl-chain-vertical-item/pearl-chain-vertical-item.spec.ts
- src/elements-experimental/pearl-chain-vertical/pearl-chain-vertical.spec.ts
- src/elements/checkbox/checkbox/checkbox.spec.ts
- src/elements/checkbox/common/checkbox-common.spec.ts
- src/elements/dialog/dialog/dialog.spec.ts
- src/elements/file-selector/common/file-selector-common.spec.ts
- src/elements/file-selector/file-selector/file-selector.spec.ts
- src/elements/icon/icon-validate.spec.ts
- src/elements/radio-button/common/radio-button-common.spec.ts
- src/elements/radio-button/radio-button-panel/radio-button-panel.spec.ts
- tools/eslint/test-describe-title-rule.ts
`xy.spec.ts` files were not included in the describe title check. With this PR it's getting included.
> build: fix eslint describe title rule

- src/elements/accordion/__snapshots__/accordion.snapshot.spec.snap.js
- src/elements/checkbox/checkbox-panel/__snapshots__/checkbox-panel.snapshot.spec.snap.js
- src/elements/core/mixins/panel-mixin.ts
- src/elements/expansion-panel/expansion-panel/__snapshots__/expansion-panel.snapshot.spec.snap.js
- src/elements/expansion-panel/expansion-panel/expansion-panel.ts
- src/elements/radio-button/radio-button-panel/__snapshots__/radio-button-panel.snapshot.spec.snap.js
- src/elements/selection-expansion-panel/__snapshots__/selection-expansion-panel.snapshot.spec.snap.js
- src/elements/selection-expansion-panel/selection-expansion-panel.ts
> fix(panels): reflect colors

- src/elements/checkbox/checkbox-group/__snapshots__/checkbox-group.snapshot.spec.snap.js
- src/elements/checkbox/checkbox-group/checkbox-group.snapshot.spec.ts
- src/elements/checkbox/checkbox-group/checkbox-group.spec.ts
- src/elements/checkbox/checkbox-group/checkbox-group.ts
- src/elements/core/mixins/panel-mixin.ts
- src/elements/radio-button/radio-button-group/__snapshots__/radio-button-group.snapshot.spec.snap.js
- src/elements/radio-button/radio-button-group/radio-button-group.snapshot.spec.ts
- src/elements/radio-button/radio-button-group/radio-button-group.spec.ts
- src/elements/radio-button/radio-button-group/radio-button-group.ts
> fix(sbb-checkbox-group, sbb-radio-button-group): fix panel detection and styling

- src/elements/autocomplete/autocomplete-base-element.ts
- src/elements/autocomplete/autocomplete.spec.ts
- src/elements/form-field/form-field/form-field.ts
- src/elements/select/select.spec.ts
- src/elements/select/select.ts
> fix(sbb-autocomplete): fix floating label flickering

- src/elements-experimental/seat-reservation/common/aria-label.ts
- src/elements-experimental/seat-reservation/common/index.ts
- src/elements-experimental/seat-reservation/common/mapper.ts
- src/elements-experimental/seat-reservation/common/navigation-icon-mapper.ts
- src/elements-experimental/seat-reservation/seat-reservation-navigation/readme.md
- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.scss
- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.stories.ts
- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.ts
- src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
- src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.ts
- src/elements-experimental/seat-reservation/seat-reservation-sample-data.ts
- src/elements-experimental/seat-reservation/seat-reservation.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
> feat(sbb-seat-reservation-navigation): initial version for seat-reservation navigation

- src/elements/clock/clock.ts
> fix(sbb-clock): fix de-sync on long-running use cases

- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
> feat(sbb-seat-reservation-inline-css): move inline styles to <style>-Block

- src/elements-experimental/seat-reservation/common/mapper.ts
- src/elements-experimental/seat-reservation/seat-reservation-sample-data.ts
> feat(sbb-seat-reservation-mock-data): add several mock data

- src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
> feat(sbb-seat-reservation-fix-wcagii-violation): fix violation

- src/elements-experimental/seat-reservation/common/mapper.ts
- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation.ts
- src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
- tools/vite/generate-react-wrappers.ts
> seat-reservation-web-component-add-interfaces

- src/elements/clock/clock.ts
> fix(sbb-clock): handle 'visibilityChange' when paused

- src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
- src/elements/autocomplete/autocomplete-base-element.ts
- src/elements/autocomplete/autocomplete.spec.ts
- src/elements/form-field/form-field/form-field.ts
- src/elements/select/select.spec.ts
- src/elements/select/select.ts
This PR Closes #3518
- close the autocomplete/autocomplete-grid if it's open and the `disabled` prop changes to true
- in sbb-select, avoid throwing error if all the options are disabled and arrow keys are pressed
> fix(sbb-select, sbb-autocomplete): edge cases related to disabled property

- src/elements/core/styles/core.scss
- src/elements/paginator/paginator/__snapshots__/paginator.snapshot.spec.snap.js
- src/elements/select/select.ts
> fix(sbb-select): adapt trigger size in light DOM to be more flexible

- src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.ts
- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.ts
- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.ts
- src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
> sk-sbb Fix imports in seat reservation web component 

- src/elements-experimental/seat-reservation/common/mapper/mapper.ts
- src/elements-experimental/seat-reservation/common/seat-reservation-sample-data.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
> Seat reservation preselected places

- src/elements/status/readme.md
- src/elements/status/status.component.ts
- src/elements/status/status.scss
> docs(sbb-status): document CSS color vars

- src/elements/core/styles/core.scss
- src/elements/form-field/form-field/form-field.scss
> fix(sbb-form-field): reduce z-index conflicts with other components

- src/elements/date-input/date-input.component.ts
- src/elements/datepicker/datepicker/datepicker.component.ts
> fix(sbb-date-input): sync state with controls and datepicker

- src/elements-experimental/seat-reservation/seat-reservation-area/seat-reservation-area.scss
- src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.scss
- src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.ts
- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.ts
- src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.stories.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
> Seat reservation scaling size

- src/elements/paginator/common/paginator-common.ts
- src/elements/paginator/compact-paginator/readme.md
- src/elements/paginator/paginator/paginator.spec.ts
- src/elements/paginator/paginator/readme.md
> feat(sbb-paginator): add convenience methods

- src/elements/table/table-wrapper/__snapshots__/table-wrapper.snapshot.spec.snap.js
- src/elements/table/table-wrapper/readme.md
- src/elements/table/table-wrapper/table-wrapper.component.ts
- src/elements/table/table-wrapper/table-wrapper.scss
- src/elements/table/table-wrapper/table-wrapper.snapshot.spec.ts
- src/elements/table/table-wrapper/table-wrapper.spec.ts
- src/elements/table/table-wrapper/table-wrapper.stories.ts
- src/elements/table/table-wrapper/table-wrapper.visual.spec.ts
> feat(sbb-table-wrapper): introduce focusable property

- src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.scss
- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.ts
- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.scss
- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.ts
- src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.ts
> feat(sbb-seat-reservation-place-indent): remove logic for offset control

- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.ts
> sekm Seat reservation web component fix import decorator

- src/elements/autocomplete/autocomplete-base-element.ts
- src/elements/autocomplete/autocomplete.spec.ts
- src/elements/chip/chip-group/chip-group.component.ts
- src/elements/chip/chip-group/chip-group.spec.ts
- src/elements/chip/chip-group/chip-group.stories.ts
- src/elements/chip/chip-group/chip-group.visual.spec.ts
BREAKING CHANGE: remove inputAutocompleteEvent const from autocomplete.ts
> fix(sbb-chip-group): avoid importing autocomplete component

- src/elements-experimental/seat-reservation/common/mapper/icon-mapper.ts
- src/elements-experimental/seat-reservation/common/mapper/seat-reservation-sample-data.ts
- src/elements-experimental/seat-reservation/common/translations/i18n.ts
- src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-assets.ts
- src/elements-experimental/seat-reservation/seat-reservation-navigation/seat-reservation-navigation-services/seat-reservation-navigation-services.component.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
> feat(latest-icons): refactored icon usage and translations

- src/elements-experimental/seat-reservation/common/mapper/seat-reservation-sample-data.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
> Seat reservation autoscroll place focus

- src/elements/popover/popover/popover.component.ts
- src/elements/popover/popover/popover.spec.ts
This PR Closes #3730 
Propedeutic to [#66](https://github.com/sbb-design-systems/lyne-angular/issues/66)
> fix(sbb-popover): improve the robustness of the initialization

- src/elements/autocomplete/autocomplete-base-element.ts
- src/elements/header/header/header.component.ts
- src/elements/menu/menu/menu.component.ts
- src/elements/menu/menu/menu.spec.ts
- src/elements/navigation/navigation-section/navigation-section.component.ts
- src/elements/navigation/navigation/navigation.component.ts
- src/elements/navigation/navigation/navigation.spec.ts
- src/elements/popover/popover/popover.component.ts
Closes [#66](https://github.com/sbb-design-systems/lyne-angular/issues/66) (with the next lyne-angular release)
> refactor: improve init flow for components with '@idReference'

- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
> feat(seat-reservation-css-cleanup): remove unnecessary css style

- src/elements-experimental/timetable-row/__snapshots__/timetable-row.snapshot.spec.snap.js
- src/elements/core/i18n/i18n.ts
- src/elements/timetable-occupancy/__snapshots__/timetable-occupancy.snapshot.spec.snap.js
- src/elements/train/train-wagon/train-wagon.spec.ts
> fix: improve translations

- src/elements/core/datetime/date-adapter.ts
- src/elements/core/datetime/native-date-adapter.spec.ts
> fix: avoid parsing 0 day/month dates

- src/elements/select/select.component.ts
- src/elements/select/select.spec.ts
> fix(sbb-select): check null value on keyboard interaction

- src/elements/core/config/config.ts
- src/elements/popover/popover/popover.component.ts
- src/elements/popover/popover/popover.spec.ts
- src/elements/popover/popover/readme.md
Closes sbb-design-systems/lyne-angular#67
> feat(sbb-popover): add global configurations for delays

- src/elements-experimental/seat-reservation/common/styles/seat-reservation-functions.scss
- src/elements-experimental/seat-reservation/common/translations/i18n.ts
- src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
- src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
- src/elements-experimental/seat-reservation/seat-reservation/readme.md
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.scss
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.stories.ts
> refactor(seat-reservation): optimize rem size calculation

- src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.component.ts
- src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
- src/elements/autocomplete/autocomplete-base-element.ts
- src/elements/autocomplete/autocomplete.component.ts
- src/elements/autocomplete/autocomplete.spec.ts
- src/elements/option/option/option-base-element.ts
> fix(sbb-autocomplete): update active option if autoActiveFirstOption is enabled and options change

- src/elements-experimental/seat-reservation/seat-reservation-area/readme.md
- src/elements-experimental/seat-reservation/seat-reservation-graphic/readme.md
- src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.component.ts
- src/elements-experimental/seat-reservation/seat-reservation-graphic/seat-reservation-graphic.stories.ts
- src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.scss
- src/elements-experimental/seat-reservation/seat-reservation-navigation-services/__snapshots__/seat-reservation-navigation-services.snapshot.spec.snap.js
- src/elements-experimental/seat-reservation/seat-reservation-navigation-services/seat-reservation-navigation-services.component.ts
- src/elements-experimental/seat-reservation/seat-reservation-place-control/readme.md
- src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.component.ts
- src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
- src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.stories.ts
- src/elements-experimental/seat-reservation/seat-reservation-scoped/seat-reservation-scoped.component.ts
- src/elements-experimental/seat-reservation/seat-reservation-scoped/seat-reservation-scoped.scss
- src/elements-experimental/seat-reservation/seat-reservation/__snapshots__/seat-reservation.snapshot.spec.snap.js
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
- `<sbb-seat-reservation-graphic>` remove input properties 'height', 'width', 'rotation', 'inverse-rotation' from component. These properties are now set via style custom properties on the host element.
- `<sbb-seat-reservation-place-control>`  remove input properties 'height', 'width', 'rotation', 'text-rotation' from component. These properties are now set via style custom properties on the host element.
> feat(seat-reservation-comp-use-stylemap): reduce comp props and use stylemap

- src/elements/autocomplete-grid/autocomplete-grid/autocomplete-grid.spec.ts
- src/elements/autocomplete/autocomplete-base-element.ts
- src/elements/autocomplete/autocomplete.spec.ts
Closes [#lyne-angular/159](https://github.com/sbb-design-systems/lyne-angular/issues/159)
> fix(sbb-autocomplete, sbb-autocomplete-grid): only opening on lazy options if count was 0

- src/elements/dialog/dialog-title/dialog-title.stories.ts
- src/elements/dialog/dialog-title/readme.md
- src/elements/journey-header/readme.md
- src/elements/sidebar/sidebar-title/readme.md
- src/elements/title/title-base.ts
- src/elements/title/title.component.ts
> docs: improve documentation of sbb-title-base derived components

- src/elements-experimental/seat-reservation/seat-reservation-place-control/seat-reservation-place-control.scss
> feat(seat reservation): distinguishing active/focus-visited state for place selection

- src/elements/dialog/dialog/__snapshots__/dialog.snapshot.spec.snap.js
- src/elements/dialog/dialog/dialog.component.ts
- src/elements/dialog/dialog/readme.md
- tools/docs/docs_generate.ts
> feat(sbb-dialog): expose CSS part of scroll-container

- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
- Popover-elements now get the 'hover-trigger' attribute, which regulates their activation-behaviour. In Desktop-mode they are activated by hovering, in responsive-mode by clicking
> feat(sbb-seat-reservation): add hover-trigger to popovers

- src/elements-experimental/seat-reservation/common/types.ts
- src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/__snapshots__/seat-reservation-navigation-coach.snapshot.spec.snap.js
- src/elements-experimental/seat-reservation/seat-reservation-navigation-coach/seat-reservation-navigation-coach.component.ts
- src/elements-experimental/seat-reservation/seat-reservation/__snapshots__/seat-reservation.snapshot.spec.snap.js
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation-base-element.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.component.ts
- src/elements-experimental/seat-reservation/seat-reservation/seat-reservation.stories.ts
> feat(seat-reservation): navigation preload and squash icons

- src/elements/toast/toast.component.ts
Closes sbb-design-systems/lyne-angular#190
> fix(sbb-toast): check for zone.js in close timeout

- src/elements/carousel/carousel/carousel.component.ts
- src/elements/carousel/carousel/carousel.scss
- src/elements/carousel/carousel/carousel.spec.ts
> fix(sbb-carousel): fix scrolling when carousel is offset
